-- Clube do Açaí: 12 unidades de 500 ml = 1 Açaí 200 ml grátis
create table if not exists public.clientes_fidelidade_acai (
  id bigint generated by default as identity primary key,
  nome text not null default 'Cliente',
  telefone text not null unique,
  pontos integer not null default 0 check (pontos >= 0),
  total_acais integer not null default 0 check (total_acais >= 0),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

alter table public.pedidos add column if not exists selos_acai_creditados integer not null default 0;

create index if not exists idx_clientes_fidelidade_acai_telefone on public.clientes_fidelidade_acai(telefone);
