-- Popular App - Central de Precificacao
-- Execute uma vez no Supabase SQL Editor.

create table if not exists public.precificacao_config (
  id text primary key default 'principal',
  taxa numeric not null default 3.5 check (taxa >= 0 and taxa < 100),
  meta numeric not null default 35 check (meta >= 0 and meta < 100),
  aluguel numeric not null default 0 check (aluguel >= 0),
  energia numeric not null default 0 check (energia >= 0),
  agua numeric not null default 0 check (agua >= 0),
  internet numeric not null default 0 check (internet >= 0),
  folha numeric not null default 0 check (folha >= 0),
  gas numeric not null default 0 check (gas >= 0),
  outros numeric not null default 0 check (outros >= 0),
  vendas integer not null default 1000 check (vendas >= 0),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.precificacao_insumos (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  compra numeric not null check (compra >= 0),
  qtd numeric not null check (qtd > 0),
  unidade text not null default 'g',
  perda numeric not null default 0 check (perda >= 0 and perda < 100),
  fornecedor text not null default '',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.precificacao_fichas (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  categoria text not null default 'Lanches',
  preco numeric not null default 0 check (preco >= 0),
  emb numeric not null default 0 check (emb >= 0),
  outros numeric not null default 0 check (outros >= 0),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.precificacao_ficha_itens (
  id bigint generated by default as identity primary key,
  ficha_id uuid not null references public.precificacao_fichas(id) on delete cascade,
  insumo_id uuid not null references public.precificacao_insumos(id) on delete restrict,
  qtd numeric not null check (qtd > 0),
  criado_em timestamptz not null default now()
);

create index if not exists idx_precificacao_itens_ficha on public.precificacao_ficha_itens(ficha_id);
create index if not exists idx_precificacao_itens_insumo on public.precificacao_ficha_itens(insumo_id);

insert into public.precificacao_config(id) values ('principal') on conflict (id) do nothing;

-- Bloqueia acesso direto via anon/authenticated. O app acessa somente pelo servidor com service role.
alter table public.precificacao_config enable row level security;
alter table public.precificacao_insumos enable row level security;
alter table public.precificacao_fichas enable row level security;
alter table public.precificacao_ficha_itens enable row level security;

revoke all on table public.precificacao_config from anon, authenticated;
revoke all on table public.precificacao_insumos from anon, authenticated;
revoke all on table public.precificacao_fichas from anon, authenticated;
revoke all on table public.precificacao_ficha_itens from anon, authenticated;
