"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
const grupos=[
 {icon:"📖",nome:"Palavra do dia",itens:["Tudo posso naquele que me fortalece. — Filipenses 4:13","O Senhor é o meu pastor; nada me faltará. — Salmos 23:1","Entrega o teu caminho ao Senhor; confia nele. — Salmos 37:5"]},
 {icon:"🙏",nome:"Oração",itens:["Orai sem cessar. — 1 Tessalonicenses 5:17","Perseverai na oração. — Colossenses 4:2","Tudo o que pedirdes em oração, crendo, recebereis. — Mateus 21:22"]},
 {icon:"❤️",nome:"Família",itens:["Eu e a minha casa serviremos ao Senhor. — Josué 24:15","O amor é paciente, o amor é bondoso. — 1 Coríntios 13:4","Acima de tudo, porém, revistam-se do amor. — Colossenses 3:14"]},
 {icon:"💪",nome:"Força",itens:["Sede fortes e corajosos; não temais. — Deuteronômio 31:6","A minha graça te basta. — 2 Coríntios 12:9","Se Deus é por nós, quem será contra nós? — Romanos 8:31"]},
 {icon:"🌅",nome:"Esperança",itens:["Alegrai-vos na esperança. — Romanos 12:12","Os que esperam no Senhor renovarão as suas forças. — Isaías 40:31","Eu é que sei que pensamentos tenho a vosso respeito, diz o Senhor. — Jeremias 29:11"]},
 {icon:"🕊️",nome:"Paz",itens:["Deixo-vos a paz, a minha paz vos dou. — João 14:27","Bem-aventurados os pacificadores. — Mateus 5:9","A paz de Deus guardará o vosso coração. — Filipenses 4:7"]},
 {icon:"🙌",nome:"Gratidão",itens:["Em tudo dai graças. — 1 Tessalonicenses 5:18","Rendei graças ao Senhor, porque ele é bom. — Salmos 136:1","Este é o dia que fez o Senhor; alegremo-nos nele. — Salmos 118:24"]}
];
export default function MomentoDeFe(){const[grupo,setGrupo]=useState(0),[troca,setTroca]=useState(0);const item=useMemo(()=>grupos[grupo].itens[troca%grupos[grupo].itens.length],[grupo,troca]);return <main className="min-h-screen bg-zinc-950 text-white px-5 pt-6 pb-28 max-w-2xl mx-auto"><div className="flex items-center gap-3"><Link href="/" className="w-11 h-11 bg-zinc-900 rounded-xl grid place-items-center">←</Link><div><p className="text-yellow-400 text-xs font-black">POPULAR • MOMENTO DE FÉ</p><h1 className="text-3xl font-black">🙏 Momento de Fé</h1></div></div><p className="text-zinc-400 mt-3">Uma pausa para fortalecer a fé, a esperança e a gratidão.</p><section className="mt-6 bg-gradient-to-br from-yellow-400 to-yellow-300 text-black rounded-3xl p-6 shadow-xl"><p className="text-xs font-black opacity-60">{grupos[grupo].icon} {grupos[grupo].nome.toUpperCase()}</p><blockquote className="text-xl font-black mt-3 leading-snug">“{item.split(" — ")[0]}”</blockquote><p className="font-bold mt-3">📖 {item.split(" — ")[1]}</p><button onClick={()=>setTroca(x=>x+1)} className="mt-5 bg-black text-white px-4 py-3 rounded-xl font-black text-sm">Outra mensagem →</button></section><h2 className="font-black text-lg mt-7">Escolha um momento</h2><div className="grid grid-cols-2 gap-3 mt-3">{grupos.map((g,i)=><button key={g.nome} onClick={()=>{setGrupo(i);setTroca(0)}} className={`text-left rounded-2xl p-4 border ${grupo===i?"bg-yellow-400 text-black border-yellow-400":"bg-zinc-900 border-zinc-800"}`}><span className="text-2xl">{g.icon}</span><b className="block mt-2">{g.nome}</b></button>)}</div><div className="mt-6 bg-zinc-900 border border-zinc-800 rounded-2xl p-4 text-center"><p className="text-sm text-zinc-400">Que esta palavra leve paz e esperança ao seu dia.</p><b className="text-yellow-400 text-sm">Deus abençoe você e sua família. ❤️</b></div></main>}
