"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
type Msg={texto:string;ref:string;reflexao:string};type Grupo={icon:string;nome:string,sub:string,itens:Msg[]};
const grupos:Grupo[]=[
{icon:"📖",nome:"Palavra do dia",sub:"Uma palavra para guiar o seu dia",itens:[
{texto:"Tudo posso naquele que me fortalece.",ref:"Filipenses 4:13",reflexao:"Você não precisa enfrentar o dia apenas com a sua própria força. Coloque seus planos diante de Deus e siga com fé."},
{texto:"O Senhor é o meu pastor; nada me faltará.",ref:"Salmos 23:1",reflexao:"Deus cuida, conduz e permanece presente. Mesmo quando não enxergamos todo o caminho, podemos confiar no Pastor."},
{texto:"Entrega o teu caminho ao Senhor; confia nele.",ref:"Salmos 37:5",reflexao:"Entregar é reconhecer que Deus vê além do que nós vemos. Faça a sua parte e confie a Ele aquilo que você não controla."},
{texto:"Este é o dia que fez o Senhor; alegremo-nos nele.",ref:"Salmos 118:24",reflexao:"Cada novo dia é uma oportunidade de agradecer, recomeçar, amar e fazer o bem."}]},
{icon:"🙏",nome:"Oração",sub:"Quando você precisa falar com Deus",itens:[
{texto:"Orai sem cessar.",ref:"1 Tessalonicenses 5:17",reflexao:"A oração não precisa de palavras difíceis. Converse com Deus com sinceridade, onde você estiver."},
{texto:"Perseverai na oração.",ref:"Colossenses 4:2",reflexao:"Nem toda resposta chega no nosso tempo. Continue orando, agradecendo e confiando."},
{texto:"Tudo o que pedirdes em oração, crendo, recebereis.",ref:"Mateus 21:22",reflexao:"Apresente seus pedidos com fé, lembrando que Deus conhece suas necessidades e sabe o que é melhor."}]},
{icon:"❤️",nome:"Família",sub:"Amor, união e cuidado dentro de casa",itens:[
{texto:"Eu e a minha casa serviremos ao Senhor.",ref:"Josué 24:15",reflexao:"Uma família fortalecida em Deus aprende a caminhar com amor, perdão, respeito e propósito."},
{texto:"O amor é paciente, o amor é bondoso.",ref:"1 Coríntios 13:4",reflexao:"Dentro de casa, pequenos gestos de paciência e bondade podem transformar relacionamentos."},
{texto:"Acima de tudo, porém, revistam-se do amor.",ref:"Colossenses 3:14",reflexao:"Que o amor seja a escolha principal nas palavras, decisões e atitudes com aqueles que Deus colocou perto de você."}]},
{icon:"💪",nome:"Força e coragem",sub:"Para os dias em que parece difícil continuar",itens:[
{texto:"Sede fortes e corajosos; não temais.",ref:"Deuteronômio 31:6",reflexao:"Coragem não significa ausência de medo. É continuar confiando que Deus está presente mesmo diante da dificuldade."},
{texto:"A minha graça te basta.",ref:"2 Coríntios 12:9",reflexao:"Há momentos em que nossas forças acabam. A graça de Deus nos lembra que não caminhamos sozinhos."},
{texto:"Se Deus é por nós, quem será contra nós?",ref:"Romanos 8:31",reflexao:"Não deixe a dificuldade definir o final da história. Mantenha a fé e prossiga."}]},
{icon:"🌅",nome:"Esperança",sub:"Para lembrar que Deus ainda está trabalhando",itens:[
{texto:"Alegrai-vos na esperança, sede pacientes na tribulação.",ref:"Romanos 12:12",reflexao:"Esperança cristã não ignora a dificuldade; ela nos ajuda a atravessá-la sem perder a fé."},
{texto:"Os que esperam no Senhor renovarão as suas forças.",ref:"Isaías 40:31",reflexao:"Esperar em Deus também é caminhar. Enquanto você espera, continue fazendo o bem e mantendo o coração firme."},
{texto:"Eu é que sei que pensamentos tenho a vosso respeito, diz o Senhor.",ref:"Jeremias 29:11",reflexao:"Nem sempre entendemos o momento presente, mas podemos descansar sabendo que nossa história não está fora das mãos de Deus."}]},
{icon:"🕊️",nome:"Paz",sub:"Para aquietar o coração",itens:[
{texto:"Deixo-vos a paz, a minha paz vos dou.",ref:"João 14:27",reflexao:"A paz de Cristo não depende de tudo estar perfeito. Ela pode habitar em nós mesmo enquanto enfrentamos problemas."},
{texto:"Bem-aventurados os pacificadores.",ref:"Mateus 5:9",reflexao:"Levar paz também é uma forma de testemunhar. Onde houver conflito, escolha palavras que curem e aproximem."},
{texto:"A paz de Deus guardará o vosso coração.",ref:"Filipenses 4:7",reflexao:"Apresente a Deus aquilo que pesa no coração e permita que a oração abra espaço para a paz."}]},
{icon:"🙌",nome:"Gratidão",sub:"Para reconhecer as bênçãos de cada dia",itens:[
{texto:"Em tudo dai graças.",ref:"1 Tessalonicenses 5:18",reflexao:"Gratidão não é dizer que tudo é fácil. É perceber que, mesmo nos dias difíceis, ainda existem motivos para reconhecer a bondade de Deus."},
{texto:"Rendei graças ao Senhor, porque ele é bom.",ref:"Salmos 136:1",reflexao:"Pare por alguns segundos e lembre-se de algo pelo qual você pode agradecer hoje."},
{texto:"Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios.",ref:"Salmos 103:2",reflexao:"Recordar o cuidado de Deus no passado fortalece a confiança para enfrentar o presente."}]},
{icon:"💼",nome:"Trabalho",sub:"Sabedoria e propósito para o trabalho",itens:[
{texto:"Tudo quanto fizerdes, fazei-o de todo o coração.",ref:"Colossenses 3:23",reflexao:"Trabalhar com dedicação, honestidade e respeito também é uma maneira de honrar a Deus."},
{texto:"Os planos do diligente tendem à abundância.",ref:"Provérbios 21:5",reflexao:"Ore, planeje, organize e trabalhe com constância. Bons resultados normalmente são construídos passo a passo."}]}
];
const oracoes=[
{titulo:"Oração para começar o dia",texto:"Senhor Deus, obrigado por mais um dia. Guia meus pensamentos, minhas palavras e minhas decisões. Dá-me sabedoria para fazer o bem, força para enfrentar as dificuldades e um coração agradecido. Guarda minha família e abençoa o trabalho das minhas mãos. Em nome de Jesus, amém."},
{titulo:"Oração pela família",texto:"Senhor, visita a minha casa e a minha família. Dá-nos união, saúde, sabedoria, paciência e amor. Ajuda-nos a perdoar, conversar e cuidar uns dos outros. Que a tua paz esteja em nosso lar. Em nome de Jesus, amém."},
{titulo:"Oração nos momentos difíceis",texto:"Deus, tu conheces aquilo que estou enfrentando. Quando minhas forças forem pequenas, sustenta-me. Dá-me serenidade para aquilo que não posso mudar, coragem para fazer o que precisa ser feito e fé para continuar. Em nome de Jesus, amém."}
];
export default function MomentoDeFe(){const[grupo,setGrupo]=useState(0),[troca,setTroca]=useState(0),[favoritos,setFavoritos]=useState<string[]>([]),[oracao,setOracao]=useState<number|null>(null),[copiado,setCopiado]=useState(false);useEffect(()=>{try{setFavoritos(JSON.parse(localStorage.getItem("popular_fe_favoritos")||"[]"))}catch{}},[]);const item=useMemo(()=>grupos[grupo].itens[troca%grupos[grupo].itens.length],[grupo,troca]);const chave=`${item.ref}|${item.texto}`;const favorito=favoritos.includes(chave);function favoritar(){const n=favorito?favoritos.filter(x=>x!==chave):[...favoritos,chave];setFavoritos(n);localStorage.setItem("popular_fe_favoritos",JSON.stringify(n))}async function compartilhar(){const texto=`🙏 Momento de Fé\n\n“${item.texto}”\n📖 ${item.ref}\n\n${item.reflexao}\n\nPopular Hambúrgueria e Sorveteria`;try{if(navigator.share)await navigator.share({title:"Momento de Fé",text:texto});else{await navigator.clipboard.writeText(texto);setCopiado(true);setTimeout(()=>setCopiado(false),1800)}}catch{}}
return <main className="min-h-screen bg-zinc-950 text-white px-5 pt-6 pb-28 max-w-2xl mx-auto"><header className="flex items-center gap-3"><Link href="/" className="w-11 h-11 bg-zinc-900 border border-zinc-800 rounded-xl grid place-items-center" aria-label="Voltar">←</Link><div><p className="text-yellow-400 text-[11px] font-black tracking-wider">POPULAR • MOMENTO DE FÉ</p><h1 className="text-3xl font-black">🙏 Momento de Fé</h1></div></header><p className="text-zinc-400 mt-3">Um cantinho de fé, esperança e gratidão para fazer bem ao coração.</p>
<section className="mt-6 relative overflow-hidden bg-gradient-to-br from-yellow-300 via-yellow-400 to-amber-500 text-black rounded-[2rem] p-6 shadow-2xl"><div className="absolute -right-5 -top-7 text-9xl opacity-[.08]">{grupos[grupo].icon}</div><div className="relative"><div className="flex justify-between gap-3"><div><p className="text-[10px] font-black tracking-[.18em] opacity-60">{grupos[grupo].icon} {grupos[grupo].nome.toUpperCase()}</p><p className="text-xs font-semibold opacity-70 mt-1">{grupos[grupo].sub}</p></div><button onClick={favoritar} aria-label="Favoritar mensagem" className="w-10 h-10 bg-black/10 rounded-full text-xl">{favorito?"❤️":"🤍"}</button></div><blockquote className="text-2xl font-black mt-5 leading-tight">“{item.texto}”</blockquote><p className="font-black mt-3">📖 {item.ref}</p><div className="h-px bg-black/15 my-5"/><p className="text-xs font-black opacity-60">PARA REFLETIR</p><p className="font-semibold leading-relaxed mt-2">{item.reflexao}</p><div className="grid grid-cols-2 gap-2 mt-5"><button onClick={()=>setTroca(x=>x+1)} className="bg-black text-white py-3 rounded-xl font-black text-sm">Outra palavra →</button><button onClick={compartilhar} className="bg-white/50 border border-black/10 py-3 rounded-xl font-black text-sm">{copiado?"✓ Copiado":"↗ Compartilhar"}</button></div></div></section>
<section className="mt-7"><div className="flex justify-between items-end"><div><p className="text-yellow-400 text-xs font-black">ENCONTRE UMA PALAVRA</p><h2 className="text-xl font-black">Como está seu coração hoje?</h2></div></div><div className="grid grid-cols-2 gap-3 mt-4">{grupos.map((g,i)=><button key={g.nome} onClick={()=>{setGrupo(i);setTroca(0);window.scrollTo({top:0,behavior:"smooth"})}} className={`text-left rounded-2xl p-4 border transition active:scale-[.98] ${grupo===i?"bg-yellow-400 text-black border-yellow-400":"bg-zinc-900 border-zinc-800"}`}><span className="text-2xl">{g.icon}</span><b className="block mt-2 text-sm">{g.nome}</b><span className={`block text-[11px] mt-1 ${grupo===i?"text-black/60":"text-zinc-500"}`}>{g.sub}</span></button>)}</div></section>
<section className="mt-7 bg-zinc-900 border border-zinc-800 rounded-3xl p-5"><p className="text-yellow-400 text-xs font-black">🙏 VAMOS ORAR?</p><h2 className="text-xl font-black mt-1">Orações para cada momento</h2><p className="text-zinc-400 text-sm mt-1">Escolha uma oração, leia com calma e fale com Deus também com suas próprias palavras.</p><div className="space-y-2 mt-4">{oracoes.map((o,i)=><div key={o.titulo} className="bg-zinc-950 border border-zinc-800 rounded-2xl overflow-hidden"><button onClick={()=>setOracao(oracao===i?null:i)} className="w-full p-4 flex justify-between items-center text-left font-black text-sm"><span>{i===0?"🌅":i===1?"❤️":"🕊️"} {o.titulo}</span><span>{oracao===i?"−":"+"}</span></button>{oracao===i&&<div className="px-4 pb-4 text-sm text-zinc-300 leading-relaxed border-t border-zinc-800 pt-3">{o.texto}</div>}</div>)}</div></section>
{favoritos.length>0&&<section className="mt-5 bg-zinc-900 border border-zinc-800 rounded-3xl p-5"><p className="text-red-400 text-xs font-black">❤️ SUAS FAVORITAS</p><h2 className="font-black text-lg mt-1">Palavras que você guardou</h2><p className="text-zinc-400 text-sm mt-1">Você tem {favoritos.length} {favoritos.length===1?"mensagem salva":"mensagens salvas"} neste aparelho.</p></section>}
<section className="mt-5 rounded-3xl p-5 text-center border border-yellow-400/15 bg-gradient-to-b from-yellow-400/5 to-transparent"><div className="text-3xl">✝️</div><p className="font-black mt-2">Deus abençoe você e sua família.</p><p className="text-zinc-500 text-xs mt-2">Que a fé acompanhe seus passos e que nunca faltem esperança, amor e gratidão.</p><p className="text-yellow-400 text-[10px] font-black tracking-widest mt-4">POPULAR HAMBURGUERIA E SORVETERIA • SINCE 2017</p></section>
</main>}
