"use client";
import {useMemo,useState} from "react";

type Props={d:any;api:(body:any)=>Promise<any>;load:()=>Promise<void>;func:string;setFunc:(v:string)=>void;setMsg:(v:string)=>void};
const money=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const data=(v:any)=>{try{return new Date(v).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}catch{return""}};
const MINIMO_SELO=20;
function semAcento(v:any){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function itemElegivel(i:any){const n=semAcento(i?.nome||"");if(/sorvete|milk\s*shake|milkshake|acai/.test(n))return false;return /misto|x-|big|lanche|hamburguer|burger|frita|batata|refrigerante|coca|kuat|guarana|monster|suco|vitamina/.test(n)}
function valorElegivel(p:any){return Number((p?.itens||[]).filter(itemElegivel).reduce((s:number,i:any)=>s+Number(i.preco||0)*Number(i.quantidade||0),0).toFixed(2))}
export default function Operacao({d,api,load,func,setFunc,setMsg}:Props){
 const[filtro,setFiltro]=useState("pedidos");const[busy,setBusy]=useState("");
 const pedidos=d?.pedidos||[],premios=d?.premios||[],anivs=d?.aniversarios||[];
 const pendentes=useMemo(()=>pedidos.filter((p:any)=>p.status==="pendente"),[pedidos]);
 const confirmados=useMemo(()=>pedidos.filter((p:any)=>p.status==="confirmado"),[pedidos]);
 async function acao(body:any,key:string,pergunta:string,sucesso:string){if(busy)return;if(!confirm(pergunta))return;setBusy(key);const r=await api(body);if(r){setMsg(`✅ ${sucesso}`);await load()}setBusy("")}
 async function acaoPedido(body:any,p:any,finalizar=false){if(busy)return;const pergunta=finalizar?"Marcar este pedido como entregue/finalizado?":"Confirmar este pedido? Se for elegível, o selo será creditado.";if(!confirm(pergunta))return;setBusy(p.pedido_id);const r=await api(body);if(r){const ve=valorElegivel(p),elegivel=ve>=MINIMO_SELO,creditado=!!r.selo_creditado||!!p.selo_creditado;let msg=finalizar?"✅ Pedido finalizado.":"✅ Pedido confirmado.";if(elegivel&&creditado)msg+=" ⭐ Selo enviado com sucesso para o Clube Popular.";else if(elegivel)msg+=" ⚠️ Pedido tem R$ 20,00 ou mais em itens elegíveis, mas o selo não foi confirmado. Verifique antes de encerrar.";else msg+=` ℹ️ Valor elegível ${money(ve)} — é necessário R$ 20,00 em lanches, fritas, refrigerantes, sucos e vitaminas para gerar selo.`;setMsg(msg);await load()}setBusy("")}
 function whats(t:any,text="Olá! Aqui é da Popular Hambúrgueria e Sorveteria 🍔"){const n=String(t||"").replace(/\D/g,"");if(n)window.open(`https://wa.me/55${n.replace(/^55/,"")}?text=${encodeURIComponent(text)}`,"_blank")}
 return <section className="mt-5 space-y-4">
  <div className="bg-gradient-to-br from-zinc-900 to-zinc-950 border border-zinc-800 rounded-3xl p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-yellow-400 text-xs font-black">⚡ CENTRAL DE OPERAÇÕES</p><h2 className="text-2xl font-black mt-1">Tudo que precisa de atenção</h2><p className="text-zinc-400 text-sm mt-1">Atualização automática do painel a cada 15 segundos.</p></div><button onClick={()=>void load()} className="bg-zinc-800 px-3 py-2 rounded-xl text-xs font-bold">↻ Atualizar</button></div><div className="grid grid-cols-3 gap-2 mt-4"><Mini n={pendentes.length} t="Novos" c="text-yellow-400"/><Mini n={confirmados.length} t="Em andamento" c="text-green-400"/><Mini n={premios.length+anivs.length} t="Atenções" c="text-orange-400"/></div></div>
  <div className="grid grid-cols-3 gap-2">{[["pedidos",`🍔 Pedidos (${pedidos.length})`],["premios",`🎁 Prêmios (${premios.length})`],["aniversarios",`🎂 Aniversários (${anivs.length})`]].map(x=><button key={x[0]} onClick={()=>setFiltro(x[0])} className={`p-3 rounded-xl text-xs font-black ${filtro===x[0]?"bg-yellow-400 text-black":"bg-zinc-900"}`}>{x[1]}</button>)}</div>
  {filtro==="pedidos"&&<div className="space-y-3">{!pedidos.length&&<Vazio icon="✅" t="Nenhum pedido aguardando ação"/>}{pedidos.map((p:any)=>{const ve=valorElegivel(p);return <article key={p.pedido_id} className={`rounded-2xl border p-4 ${p.status==="pendente"?"bg-yellow-400/5 border-yellow-400/30":"bg-zinc-900 border-zinc-800"}`}><div className="flex justify-between gap-3"><div><div className="flex gap-2 items-center"><span className={`text-[10px] font-black px-2 py-1 rounded-full ${p.status==="pendente"?"bg-yellow-400 text-black":"bg-green-500/20 text-green-400"}`}>{p.status==="pendente"?"NOVO • CONFIRMAR":"EM ANDAMENTO"}</span><span className="text-xs text-zinc-500">{data(p.criado_em)}</span></div><h3 className="font-black text-lg mt-2">{p.nome_cliente}</h3><p className="text-zinc-400 text-sm">📱 {p.whatsapp}</p></div><b className="text-yellow-400">{money(p.total)}</b></div><div className="bg-zinc-950 rounded-xl p-3 mt-3 text-sm">{(p.itens||[]).map((i:any,k:number)=><div key={k} className="flex justify-between gap-2 py-1"><span>{i.quantidade}x {i.nome}</span><span className="text-zinc-500">{money(Number(i.preco)*Number(i.quantidade))}</span></div>)}</div><div className={`mt-3 rounded-xl p-3 text-xs font-bold ${ve>=MINIMO_SELO?"bg-green-500/10 text-green-300":"bg-zinc-800 text-zinc-400"}`}>⭐ Valor elegível para selo: {money(ve)} {ve>=MINIMO_SELO?"• ELEGÍVEL":"• NÃO ELEGÍVEL"}</div><p className="text-sm text-zinc-300 mt-3">{p.tipo_entrega==="retirada"?"🏪 Retirada no local":`🛵 ${p.endereco_entrega||"Entrega"}`}</p><div className="grid grid-cols-2 gap-2 mt-3"><button onClick={()=>whats(p.whatsapp)} className="bg-green-600 text-white p-3 rounded-xl font-black text-sm">💬 WhatsApp</button>{p.status==="pendente"?<button disabled={!!busy} onClick={()=>void acaoPedido({action:"confirmar_pedido",pedido_id:p.pedido_id},p)} className="bg-yellow-400 text-black p-3 rounded-xl font-black text-sm">{busy===p.pedido_id?"Confirmando...":"✓ Confirmar pedido"}</button>:<button disabled={!!busy} onClick={()=>void acaoPedido({action:"confirmar_entrega",pedido_id:p.pedido_id},p,true)} className="bg-blue-600 p-3 rounded-xl font-black text-sm">{busy===p.pedido_id?"Finalizando...":"✓ Entregue / Finalizar"}</button>}</div></article>})}</div>}
  {filtro==="premios"&&<div className="space-y-3">{!premios.length&&<Vazio icon="🎁" t="Nenhum prêmio aguardando resgate"/>}{premios.map((p:any)=><article key={p.id} className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4"><div className="flex justify-between"><div><h3 className="font-black">🎁 {p.nome}</h3><p className="text-zinc-400 text-sm">📱 {p.telefone}</p></div><div className="text-right"><b className="text-yellow-400 text-xl">{p.pontos}</b><p className="text-[10px] text-zinc-500">SELOS</p></div></div><p className="text-xs text-zinc-400 mt-2">Prêmio disponível a partir de 12 selos: 1 X-Salada grátis.</p><div className="grid grid-cols-2 gap-2 mt-3"><button onClick={()=>whats(p.telefone,"Olá! Você tem prêmio disponível na fidelidade da Popular 🍔🎁")} className="bg-green-600 p-3 rounded-xl font-black text-sm">💬 Avisar cliente</button><button disabled={!!busy} onClick={()=>acao({action:"resgatar_xsalada",telefone:p.telefone},`r${p.id}`,"Confirmar a entrega de 1 X-Salada grátis? Serão descontados 12 selos.","Prêmio resgatado com segurança.")} className="bg-yellow-400 text-black p-3 rounded-xl font-black text-sm">🎁 Entregar prêmio</button></div></article>)}</div>}
  {filtro==="aniversarios"&&<div><div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4"><label className="text-xs font-black text-zinc-400">RESPONSÁVEL PELA CONFERÊNCIA</label><input value={func} onChange={e=>{setFunc(e.target.value);localStorage.setItem("popular_admin_funcionario",e.target.value)}} placeholder="Nome de quem conferiu o documento" className="w-full bg-zinc-800 p-3 rounded-xl mt-2"/><p className="text-[11px] text-zinc-500 mt-2">Confira presencialmente um documento oficial com foto antes de aprovar.</p></div>{!anivs.length&&<Vazio icon="🎂" t="Nenhum aniversário aguardando conferência"/>}{anivs.map((a:any)=><article key={a.id} className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4 mt-3"><h3 className="font-black">🎂 {a.nome}</h3><p className="text-zinc-400 text-sm mt-1">📱 {a.telefone} • Data informada: <b className="text-white">{String(a.aniversario_dia).padStart(2,"0")}/{String(a.aniversario_mes).padStart(2,"0")}</b></p><div className="grid grid-cols-3 gap-2 mt-3"><button onClick={()=>whats(a.telefone)} className="bg-green-600 p-3 rounded-xl font-black text-xs">WhatsApp</button><button disabled={!func.trim()||!!busy} onClick={()=>acao({action:"verificar_aniversario",telefone:a.telefone,funcionario:func},`a${a.id}`,`Você conferiu o documento oficial de ${a.nome} e a data está correta?`,`Aniversário verificado por ${func}.`)} className="bg-yellow-400 disabled:opacity-40 text-black p-3 rounded-xl font-black text-xs">✓ Aprovar</button><button disabled={!func.trim()||!!busy} onClick={()=>{const motivo=prompt("Motivo da recusa (opcional):")??"";void acao({action:"recusar_aniversario",telefone:a.telefone,funcionario:func,motivo},`x${a.id}`,"Recusar esta data? O cliente precisará cadastrá-la novamente.","Cadastro recusado.")}} className="bg-red-900 disabled:opacity-40 p-3 rounded-xl font-black text-xs">✕ Recusar</button></div></article>)}</div>}
 </section>
}
function Mini({n,t,c}:{n:number;t:string;c:string}){return <div className="bg-zinc-950 rounded-2xl p-3 text-center"><b className={`text-2xl ${c}`}>{n}</b><p className="text-[10px] text-zinc-500 font-bold mt-1">{t}</p></div>}
function Vazio({icon,t}:{icon:string;t:string}){return <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-8 text-center mt-3"><div className="text-4xl">{icon}</div><b className="block mt-2">{t}</b><p className="text-zinc-500 text-xs mt-1">A central está em dia.</p></div>}
