"use client";
import Link from "next/link";
import {useMemo,useState} from "react";

type Produto={id:number;nome:string;categoria:string;preco:number;estoque:number;oferta:boolean;ativo:boolean};
const inicial:Produto[]=[
{id:1,nome:"Arroz Tipo 1 5kg",categoria:"Mercearia",preco:27.9,estoque:36,oferta:true,ativo:true},
{id:2,nome:"Feijão Carioca 1kg",categoria:"Mercearia",preco:7.49,estoque:54,oferta:true,ativo:true},
{id:3,nome:"Leite Integral 1L",categoria:"Laticínios",preco:4.79,estoque:22,oferta:false,ativo:true},
{id:4,nome:"Banana Prata kg",categoria:"Hortifruti",preco:4.49,estoque:18,oferta:true,ativo:true},
{id:5,nome:"Detergente 500ml",categoria:"Limpeza",preco:2.79,estoque:8,oferta:false,ativo:true},
{id:6,nome:"Café 500g",categoria:"Mercearia",preco:19.9,estoque:14,oferta:true,ativo:true},
];
const cats=["Todos","Mercearia","Hortifruti","Carnes","Padaria","Frios","Laticínios","Bebidas","Limpeza","Higiene","Congelados","Pet","Bebê"];
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function Admin(){
 const[tab,setTab]=useState("geral");const[produtos,setProdutos]=useState(inicial);const[busca,setBusca]=useState("");const[cat,setCat]=useState("Todos");const[msg,setMsg]=useState("");
 const filtrados=useMemo(()=>produtos.filter(p=>(cat==="Todos"||p.categoria===cat)&&p.nome.toLowerCase().includes(busca.toLowerCase())),[produtos,cat,busca]);
 const estoqueBaixo=produtos.filter(p=>p.estoque<=10).length;const ofertas=produtos.filter(p=>p.oferta).length;const ativos=produtos.filter(p=>p.ativo).length;
 function alterar(id:number,campo:keyof Produto,valor:any){setProdutos(ps=>ps.map(p=>p.id===id?{...p,[campo]:valor}:p));setMsg("✅ Alteração salva no protótipo.");setTimeout(()=>setMsg(""),1400)}
 function novo(){const id=Math.max(...produtos.map(p=>p.id))+1;setProdutos([{id,nome:"Novo produto",categoria:"Mercearia",preco:0,estoque:0,oferta:false,ativo:true},...produtos]);setTab("produtos")}
 return <main className="min-h-screen bg-[#f6f7f9] text-zinc-900 p-4 pb-24"><div className="max-w-5xl mx-auto"><header className="flex items-start justify-between gap-4"><div><p className="text-xs font-black text-emerald-700 uppercase">Mercado Fácil • Administração</p><h1 className="text-3xl font-black">Painel do supermercado</h1><p className="text-sm text-zinc-500 mt-1">Protótipo administrativo baseado na estrutura do Popular Gestão.</p></div><Link href="/" className="bg-white border border-zinc-200 px-4 py-3 rounded-xl font-black">Ver loja</Link></header>
<nav className="grid grid-cols-4 gap-2 mt-5">{[["geral","📊 Geral"],["produtos","📦 Produtos"],["ofertas","🏷️ Ofertas"],["config","⚙️ Loja"]].map(([k,n])=><button key={k} onClick={()=>setTab(k)} className={`p-3 rounded-xl font-black text-xs ${tab===k?"bg-emerald-700 text-white":"bg-white border border-zinc-200"}`}>{n}</button>)}</nav>
{tab==="geral"&&<><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-5"><K t="Produtos ativos" v={ativos}/><K t="Ofertas" v={ofertas}/><K t="Estoque baixo" v={estoqueBaixo}/><K t="Venda demo hoje" v="R$ 1.284"/></div><section className="mt-4 bg-white border border-zinc-200 rounded-3xl p-5"><h2 className="text-xl font-black">Alertas</h2><div className="mt-3 space-y-2">{produtos.filter(p=>p.estoque<=10).map(p=><div key={p.id} className="flex justify-between bg-red-50 text-red-900 rounded-xl p-3"><span>⚠️ {p.nome}</span><b>{p.estoque} un.</b></div>)}</div></section></>}
{tab==="produtos"&&<section className="mt-5"><div className="flex gap-2"><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar produto" className="flex-1 bg-white border border-zinc-200 rounded-xl p-3"/><button onClick={novo} className="bg-emerald-700 text-white px-4 rounded-xl font-black">+ Novo</button></div><div className="flex gap-2 overflow-x-auto py-3">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={`whitespace-nowrap px-3 py-2 rounded-full text-xs font-bold ${cat===c?"bg-emerald-700 text-white":"bg-white border border-zinc-200"}`}>{c}</button>)}</div><div className="space-y-3">{filtrados.map(p=><article key={p.id} className="bg-white border border-zinc-200 rounded-2xl p-4"><div className="flex justify-between gap-3"><div><input value={p.nome} onChange={e=>alterar(p.id,"nome",e.target.value)} className="font-black bg-transparent outline-none w-full"/><p className="text-xs text-zinc-500 mt-1">{p.categoria}</p></div><label className="text-xs font-bold"><input type="checkbox" checked={p.ativo} onChange={e=>alterar(p.id,"ativo",e.target.checked)}/> Ativo</label></div><div className="grid grid-cols-3 gap-2 mt-3"><label className="text-[11px] text-zinc-500">Preço<input type="number" step="0.01" value={p.preco} onChange={e=>alterar(p.id,"preco",Number(e.target.value))} className="w-full bg-zinc-100 p-2 rounded-lg text-zinc-900 mt-1"/></label><label className="text-[11px] text-zinc-500">Estoque<input type="number" value={p.estoque} onChange={e=>alterar(p.id,"estoque",Number(e.target.value))} className="w-full bg-zinc-100 p-2 rounded-lg text-zinc-900 mt-1"/></label><label className="text-[11px] text-zinc-500">Oferta<select value={p.oferta?"sim":"nao"} onChange={e=>alterar(p.id,"oferta",e.target.value==="sim")} className="w-full bg-zinc-100 p-2 rounded-lg text-zinc-900 mt-1"><option value="sim">Sim</option><option value="nao">Não</option></select></label></div></article>)}</div></section>}
{tab==="ofertas"&&<section className="mt-5 grid md:grid-cols-2 gap-3">{produtos.filter(p=>p.oferta).map(p=><div key={p.id} className="bg-white border border-zinc-200 rounded-3xl p-5"><p className="text-xs font-black text-red-600">OFERTA ATIVA</p><h3 className="font-black text-lg mt-1">{p.nome}</h3><p className="text-2xl font-black text-emerald-700 mt-2">{money(p.preco)}</p><button onClick={()=>alterar(p.id,"oferta",false)} className="mt-3 bg-zinc-900 text-white px-4 py-2 rounded-xl font-black text-sm">Encerrar oferta</button></div>)}</section>}
{tab==="config"&&<section className="mt-5 bg-white border border-zinc-200 rounded-3xl p-5 space-y-3"><h2 className="text-xl font-black">Informações da loja</h2><input placeholder="Nome do supermercado" defaultValue="Mercado Fácil" className="w-full bg-zinc-100 rounded-xl p-3"/><input placeholder="WhatsApp" className="w-full bg-zinc-100 rounded-xl p-3"/><input placeholder="Endereço" className="w-full bg-zinc-100 rounded-xl p-3"/><input placeholder="Taxa de entrega" className="w-full bg-zinc-100 rounded-xl p-3"/><button onClick={()=>{setMsg("✅ Configurações salvas no protótipo.");setTimeout(()=>setMsg(""),1400)}} className="bg-emerald-700 text-white px-5 py-3 rounded-xl font-black">Salvar</button></section>}
{msg&&<div className="sticky bottom-3 mt-4 bg-zinc-900 text-white rounded-xl p-3 text-center font-black">{msg}</div>}</div></main>
}
function K({t,v}:{t:string;v:string|number}){return <div className="bg-white border border-zinc-200 rounded-2xl p-4"><p className="text-xs text-zinc-500">{t}</p><b className="text-2xl block mt-1">{v}</b></div>}
