"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {ChevronRight,Gift,MapPin,Pencil,Phone,ReceiptText,Save,ShoppingBag,Star,UserRound,X,RefreshCw} from "lucide-react";
type PerfilSalvo={nome:string;telefone:string;endereco:string};type Conta={pontos:number;total_pedidos:number;total_gasto:number};
const PERFIL_KEY="popular_perfil_cliente",DADOS_PEDIDO_KEY="popular_dados_cliente";
export default function Perfil(){
 const[perfil,setPerfil]=useState<PerfilSalvo>({nome:"Cliente Popular",telefone:"",endereco:""});const[rascunho,setRascunho]=useState<PerfilSalvo>({nome:"",telefone:"",endereco:""});const[conta,setConta]=useState<Conta|null>(null);const[editando,setEditando]=useState(false);const[salvo,setSalvo]=useState(false);const[loading,setLoading]=useState(false);const[status,setStatus]=useState("");
 async function sincronizar(dados:PerfilSalvo){const tel=dados.telefone.replace(/\D/g,"");if(tel.length<10){setConta(null);return}setLoading(true);setStatus("");try{const r=await fetch(`/api/perfil?telefone=${encodeURIComponent(tel)}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Erro");if(j.cliente){setConta({pontos:Number(j.cliente.pontos||0),total_pedidos:Number(j.cliente.total_pedidos||0),total_gasto:Number(j.cliente.total_gasto||0)});if((!dados.nome||dados.nome==="Cliente Popular")&&j.cliente.nome){const novo={...dados,nome:j.cliente.nome};setPerfil(novo);setRascunho(novo);localStorage.setItem(PERFIL_KEY,JSON.stringify(novo))}}else setConta({pontos:0,total_pedidos:(j.pedidos||[]).length,total_gasto:0})}catch{setStatus("Não foi possível sincronizar agora.")}finally{setLoading(false)}}
 useEffect(()=>{try{const proprio=localStorage.getItem(PERFIL_KEY),pedido=localStorage.getItem(DADOS_PEDIDO_KEY),origem=proprio?JSON.parse(proprio):pedido?JSON.parse(pedido):null;const dados=origem?{nome:String(origem.nome||"Cliente Popular"),telefone:String(origem.telefone||""),endereco:String(origem.endereco||"")}:{nome:"Cliente Popular",telefone:"",endereco:""};setPerfil(dados);setRascunho(dados);void sincronizar(dados)}catch{}},[]);
 function abrirEdicao(){setRascunho(perfil);setSalvo(false);setEditando(true)}
 function salvar(){const tel=rascunho.telefone.replace(/\D/g,"");if(tel&&tel.length<10){alert("Digite um WhatsApp válido com DDD.");return}const dados={nome:rascunho.nome.trim()||"Cliente Popular",telefone:tel,endereco:rascunho.endereco.trim()};localStorage.setItem(PERFIL_KEY,JSON.stringify(dados));try{const atual=JSON.parse(localStorage.getItem(DADOS_PEDIDO_KEY)||"{}");localStorage.setItem(DADOS_PEDIDO_KEY,JSON.stringify({...atual,...dados}));if(tel)localStorage.setItem("popular-fidelidade-telefone",tel)}catch{}setPerfil(dados);setRascunho(dados);setEditando(false);setSalvo(true);void sincronizar(dados);setTimeout(()=>setSalvo(false),2500)}
 const primeiroNome=perfil.nome.split(" ")[0]||"Cliente";const moeda=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
 return <main className="min-h-screen bg-zinc-950 text-white px-4 pt-8 pb-28"><div className="max-w-xl mx-auto space-y-4"><header className="flex items-center justify-between px-1"><div><p className="text-yellow-400 text-xs font-black uppercase tracking-wider">Minha conta</p><h1 className="text-3xl font-black">Olá, {primeiroNome} 👋</h1></div><div className="flex gap-2"><button onClick={()=>sincronizar(perfil)} disabled={loading} aria-label="Atualizar" className="w-11 h-11 rounded-2xl bg-zinc-900 border border-zinc-800 flex items-center justify-center"><RefreshCw size={18} className={loading?"animate-spin":""}/></button><button onClick={abrirEdicao} aria-label="Editar perfil" className="w-11 h-11 rounded-2xl bg-zinc-900 border border-zinc-800 flex items-center justify-center"><Pencil size={19}/></button></div></header>
 <section className="bg-zinc-900 border border-zinc-800 rounded-3xl p-6 shadow-xl"><div className="flex items-center gap-4"><div className="w-16 h-16 rounded-2xl bg-yellow-400 text-black flex items-center justify-center shrink-0"><UserRound size={34}/></div><div className="min-w-0 flex-1"><h2 className="text-xl font-black truncate">{perfil.nome}</h2><div className="flex items-center gap-1 text-yellow-400 text-sm font-bold mt-1"><Star size={15} fill="currentColor"/> Clube Popular</div>{perfil.telefone&&<p className="text-zinc-400 text-sm mt-1">{perfil.telefone}</p>}</div></div>{conta&&<div className="grid grid-cols-3 gap-2 mt-5"><div className="bg-zinc-800 rounded-xl p-3 text-center"><b className="text-yellow-400 text-xl">{conta.pontos}</b><p className="text-[11px] text-zinc-400">Selos</p></div><div className="bg-zinc-800 rounded-xl p-3 text-center"><b className="text-xl">{conta.total_pedidos}</b><p className="text-[11px] text-zinc-400">Pedidos</p></div><div className="bg-zinc-800 rounded-xl p-3 text-center"><b className="text-green-400 text-sm">{moeda(conta.total_gasto)}</b><p className="text-[11px] text-zinc-400">Compras</p></div></div>}{salvo&&<div className="mt-4 bg-green-500/10 border border-green-500/30 text-green-400 text-sm font-bold rounded-xl p-3">✓ Perfil atualizado.</div>}{status&&<p className="text-xs text-zinc-400 mt-3">{status}</p>}</section>
 <section className="grid grid-cols-2 gap-3"><Link href="/biblioteca/pedidos" className="bg-zinc-900 border border-zinc-800 rounded-2xl p-5 active:scale-[.98] transition"><ReceiptText size={22} className="text-yellow-400"/><b className="block mt-3">Meus pedidos</b><span className="text-xs text-zinc-400">Histórico de compras</span></Link><Link href="/fidelidade" className="bg-zinc-900 border border-zinc-800 rounded-2xl p-5 active:scale-[.98] transition"><Gift size={22} className="text-green-400"/><b className="block mt-3">Clube Popular</b><span className="text-xs text-zinc-400">Selos e recompensa</span></Link></section>
 <section className="bg-zinc-900 border border-zinc-800 rounded-3xl overflow-hidden"><div className="px-5 pt-5 pb-2"><p className="text-xs text-yellow-400 font-black uppercase">Seus dados</p><h3 className="text-lg font-black">Informações para pedidos</h3></div><button onClick={abrirEdicao} className="w-full px-5 py-4 flex items-center gap-3 text-left border-t border-zinc-800"><Phone size={19} className="text-zinc-400"/><div className="flex-1 min-w-0"><p className="text-sm font-bold">WhatsApp</p><p className="text-xs text-zinc-400 truncate">{perfil.telefone||"Adicionar telefone"}</p></div><ChevronRight size={18}/></button><button onClick={abrirEdicao} className="w-full px-5 py-4 flex items-center gap-3 text-left border-t border-zinc-800"><MapPin size={19} className="text-zinc-400"/><div className="flex-1 min-w-0"><p className="text-sm font-bold">Endereço padrão</p><p className="text-xs text-zinc-400 truncate">{perfil.endereco||"Adicionar endereço para entrega"}</p></div><ChevronRight size={18}/></button></section>
 <Link href="/cardapio" className="w-full bg-yellow-400 text-black py-4 rounded-2xl font-black flex items-center justify-center gap-2"><ShoppingBag size={20}/> Fazer novo pedido</Link><p className="text-center text-xs text-zinc-600">Nome, WhatsApp e endereço ficam salvos neste aparelho. Selos e compras são sincronizados com a Popular.</p></div>
 {editando&&<div className="fixed inset-0 z-50 bg-black/75 flex items-end sm:items-center justify-center"><div className="w-full max-w-lg bg-zinc-900 border border-zinc-700 rounded-t-3xl sm:rounded-3xl p-6"><div className="flex justify-between"><div><p className="text-yellow-400 text-xs font-black">PERFIL</p><h2 className="text-2xl font-black">Editar meus dados</h2></div><button onClick={()=>setEditando(false)} className="w-10 h-10 bg-zinc-800 rounded-xl flex items-center justify-center"><X/></button></div><div className="space-y-3 mt-6"><input value={rascunho.nome} onChange={e=>setRascunho({...rascunho,nome:e.target.value})} autoComplete="name" className="w-full bg-zinc-800 border border-zinc-700 rounded-xl p-4" placeholder="Seu nome"/><input value={rascunho.telefone} onChange={e=>setRascunho({...rascunho,telefone:e.target.value})} inputMode="tel" autoComplete="tel" className="w-full bg-zinc-800 border border-zinc-700 rounded-xl p-4" placeholder="WhatsApp com DDD"/><input value={rascunho.endereco} onChange={e=>setRascunho({...rascunho,endereco:e.target.value})} autoComplete="street-address" className="w-full bg-zinc-800 border border-zinc-700 rounded-xl p-4" placeholder="Rua, número, bairro e referência"/></div><button onClick={salvar} className="mt-6 w-full bg-yellow-400 text-black py-4 rounded-2xl font-black flex items-center justify-center gap-2"><Save size={19}/> Salvar alterações</button></div></div>}</main>;
}
