"use client";

import Link from "next/link";
import { useState } from "react";
import { useCart } from "../context/CartContext";

const brl=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function Carrinho(){
 const {items,total,adicionar,diminuir,remover,limpar}=useCart();
 const [tipo,setTipo]=useState<"entrega"|"retirada">("entrega");
 const [cupom,setCupom]=useState("");
 const [cupomOk,setCupomOk]=useState(false);
 const desconto=cupomOk?Math.min(total*0.05,20):0;
 const taxa=tipo==="entrega"&&items.length?6.9:0;
 const totalFinal=Math.max(0,total-desconto+taxa);
 function aplicar(){setCupomOk(cupom.trim().toUpperCase()==="MERCADO5")}
 if(!items.length)return <main className="min-h-screen bg-[#f6f7f9] text-zinc-900 p-5"><div className="max-w-lg mx-auto"><Link href="/" className="text-sm font-bold text-emerald-700">← Início</Link><div className="bg-white border border-zinc-200 rounded-3xl p-8 text-center mt-8 shadow-sm"><div className="text-6xl">🛒</div><h1 className="text-2xl font-black mt-3">Seu carrinho está vazio</h1><p className="text-zinc-500 mt-2">Adicione produtos do catálogo para começar sua compra.</p><Link href="/cardapio" className="block bg-emerald-700 text-white rounded-2xl py-4 font-black mt-6">Ver produtos</Link></div></div></main>;
 return <main className="min-h-screen bg-[#f6f7f9] text-zinc-900 pb-32"><header className="bg-white border-b border-zinc-200 px-4 py-4"><div className="max-w-3xl mx-auto flex items-center justify-between"><div><p className="text-xs font-black text-emerald-700 uppercase">Mercado Fácil</p><h1 className="text-2xl font-black">Seu carrinho</h1></div><Link href="/cardapio" className="text-sm font-black text-emerald-700">+ Produtos</Link></div></header><div className="max-w-3xl mx-auto p-4 space-y-4">
  <section className="space-y-3">{items.map(i=><div key={i.id} className="bg-white border border-zinc-200 rounded-2xl p-4 shadow-sm"><div className="flex justify-between gap-3"><div className="min-w-0"><h3 className="font-black leading-tight">{i.nome}</h3><p className="text-sm text-emerald-700 font-bold mt-1">{brl(i.preco)} cada</p></div><button onClick={()=>remover(i.id)} className="w-10 h-10 rounded-xl bg-zinc-100 font-black">×</button></div><div className="flex items-center justify-between mt-4"><div className="flex items-center bg-zinc-100 rounded-xl overflow-hidden"><button onClick={()=>diminuir(i.id)} className="w-11 h-11 font-black text-xl">−</button><span className="min-w-10 text-center font-black">{i.quantidade}</span><button onClick={()=>adicionar({id:i.id,nome:i.nome,preco:i.preco})} className="w-11 h-11 font-black text-xl">+</button></div><b className="text-lg">{brl(i.preco*i.quantidade)}</b></div></div>)}</section>
  <section className="bg-white border border-zinc-200 rounded-3xl p-4 shadow-sm"><h2 className="font-black text-lg">Como quer receber?</h2><div className="grid grid-cols-2 gap-2 mt-3"><button onClick={()=>setTipo("entrega")} className={`rounded-2xl p-4 text-left border ${tipo==="entrega"?"border-emerald-600 bg-emerald-50":"border-zinc-200"}`}><div className="text-2xl">🚚</div><b className="block mt-1">Entrega</b><span className="text-xs text-zinc-500">Receba em casa</span></button><button onClick={()=>setTipo("retirada")} className={`rounded-2xl p-4 text-left border ${tipo==="retirada"?"border-emerald-600 bg-emerald-50":"border-zinc-200"}`}><div className="text-2xl">🏪</div><b className="block mt-1">Retirada</b><span className="text-xs text-zinc-500">Retire na loja</span></button></div></section>
  <section className="bg-white border border-zinc-200 rounded-3xl p-4 shadow-sm"><h2 className="font-black text-lg">Cupom</h2><div className="flex gap-2 mt-3"><input value={cupom} onChange={e=>{setCupom(e.target.value);setCupomOk(false)}} placeholder="Digite seu cupom" className="min-w-0 flex-1 border border-zinc-300 rounded-xl px-3 text-base"/><button onClick={aplicar} className="bg-zinc-900 text-white px-4 rounded-xl font-black">Aplicar</button></div><p className={`text-xs mt-2 ${cupomOk?"text-emerald-700":"text-zinc-500"}`}>{cupomOk?"✓ Cupom MERCADO5 aplicado: 5% de desconto.":"Teste este protótipo com o cupom MERCADO5."}</p></section>
  <section className="bg-white border border-zinc-200 rounded-3xl p-4 shadow-sm"><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-zinc-500">Subtotal</span><b>{brl(total)}</b></div>{desconto>0&&<div className="flex justify-between text-emerald-700"><span>Desconto</span><b>− {brl(desconto)}</b></div>}<div className="flex justify-between"><span className="text-zinc-500">{tipo==="entrega"?"Taxa de entrega":"Retirada"}</span><b>{tipo==="entrega"?brl(taxa):"Grátis"}</b></div><div className="flex justify-between text-xl pt-3 mt-3 border-t border-zinc-200"><span className="font-black">Total</span><b className="text-emerald-700">{brl(totalFinal)}</b></div></div></section>
  <section className="bg-amber-50 border border-amber-200 rounded-2xl p-4"><b className="text-amber-900">🔄 Produto em falta?</b><p className="text-sm text-amber-800 mt-1">No checkout completo, o cliente poderá escolher se aceita substituição por item semelhante ou prefere remover o produto.</p></section>
  <div className="grid grid-cols-2 gap-2"><button onClick={limpar} className="border border-zinc-300 bg-white rounded-2xl py-4 font-black">Esvaziar</button><Link href="/checkout" className="bg-emerald-700 text-white rounded-2xl py-4 font-black text-center">Continuar →</Link></div>
 </div></main>
}
