export type FashionProduct={id:number;nome:string;categoria:string;genero:"Feminino"|"Masculino"|"Unissex";preco:number;precoAntigo?:number;cores:string[];tamanhos:string[];emoji:string;tag?:string;descricao:string;material:string;avaliacao:number;reviews:number;estoque:number;novo?:boolean;destaque?:boolean};

export const fashionCategories=["Novidades","Feminino","Masculino","Camisetas","Camisas","Calças","Vestidos","Conjuntos","Jaquetas","Moda Fitness","Acessórios","Promoções"];

export const fashionProducts:FashionProduct[]=[
{id:501,nome:"Vestido Midi Elegance",categoria:"Vestidos",genero:"Feminino",preco:129.9,precoAntigo:159.9,cores:["Preto","Vinho","Bege"],tamanhos:["P","M","G","GG"],emoji:"👗",tag:"-19%",descricao:"Vestido midi de caimento leve para looks elegantes e versáteis.",material:"Viscose com elastano",avaliacao:4.9,reviews:84,estoque:18,novo:true,destaque:true},
{id:502,nome:"Camiseta Premium Essential",categoria:"Camisetas",genero:"Unissex",preco:59.9,cores:["Branco","Preto","Azul","Verde"],tamanhos:["P","M","G","GG","XG"],emoji:"👕",tag:"BEST",descricao:"Camiseta básica premium com toque macio e modelagem moderna.",material:"Algodão penteado",avaliacao:4.8,reviews:132,estoque:42,destaque:true},
{id:503,nome:"Camisa Social Slim",categoria:"Camisas",genero:"Masculino",preco:99.9,precoAntigo:119.9,cores:["Branco","Azul","Preto"],tamanhos:["P","M","G","GG"],emoji:"👔",tag:"OFERTA",descricao:"Camisa social slim para trabalho, eventos e combinações casuais.",material:"Algodão e poliéster",avaliacao:4.7,reviews:61,estoque:25,destaque:true},
{id:504,nome:"Calça Jeans Reta",categoria:"Calças",genero:"Feminino",preco:119.9,cores:["Jeans claro","Jeans médio","Preto"],tamanhos:["36","38","40","42","44","46"],emoji:"👖",descricao:"Jeans de cintura alta e corte reto, confortável para o dia todo.",material:"Denim com elastano",avaliacao:4.8,reviews:97,estoque:31,novo:true},
{id:505,nome:"Calça Chino Urban",categoria:"Calças",genero:"Masculino",preco:109.9,cores:["Caqui","Preto","Marinho"],tamanhos:["38","40","42","44","46"],emoji:"👖",descricao:"Chino moderna com acabamento limpo e tecido confortável.",material:"Sarja premium",avaliacao:4.6,reviews:45,estoque:22},
{id:506,nome:"Conjunto Alfaiataria",categoria:"Conjuntos",genero:"Feminino",preco:189.9,precoAntigo:229.9,cores:["Bege","Preto","Terracota"],tamanhos:["P","M","G"],emoji:"🧥",tag:"-17%",descricao:"Conjunto de blazer leve e calça para um visual sofisticado.",material:"Alfaiataria leve",avaliacao:4.9,reviews:56,estoque:14,destaque:true},
{id:507,nome:"Jaqueta Jeans Classic",categoria:"Jaquetas",genero:"Unissex",preco:159.9,cores:["Jeans médio","Jeans escuro"],tamanhos:["P","M","G","GG"],emoji:"🧥",descricao:"Jaqueta jeans clássica com lavagem moderna e bolsos funcionais.",material:"Denim 100% algodão",avaliacao:4.8,reviews:74,estoque:19},
{id:508,nome:"Top Fitness Performance",categoria:"Moda Fitness",genero:"Feminino",preco:69.9,cores:["Preto","Rosa","Verde"],tamanhos:["P","M","G"],emoji:"🎽",tag:"NOVO",descricao:"Top fitness de média sustentação e secagem rápida.",material:"Poliamida e elastano",avaliacao:4.7,reviews:39,estoque:27,novo:true},
{id:509,nome:"Legging Sculpt",categoria:"Moda Fitness",genero:"Feminino",preco:89.9,cores:["Preto","Grafite","Vinho"],tamanhos:["P","M","G","GG"],emoji:"🩳",descricao:"Legging de cintura alta com compressão confortável.",material:"Poliamida premium",avaliacao:4.8,reviews:103,estoque:34},
{id:510,nome:"Moletom Oversized",categoria:"Jaquetas",genero:"Unissex",preco:139.9,cores:["Mescla","Preto","Areia"],tamanhos:["P","M","G","GG"],emoji:"🧥",tag:"TREND",descricao:"Moletom oversized com interior macio e visual urbano.",material:"Algodão e poliéster",avaliacao:4.9,reviews:88,estoque:16,novo:true},
{id:511,nome:"Short Alfaiataria",categoria:"Calças",genero:"Feminino",preco:79.9,cores:["Bege","Preto","Off-white"],tamanhos:["36","38","40","42","44"],emoji:"🩳",descricao:"Short estruturado com cintura alta para looks casuais elegantes.",material:"Alfaiataria",avaliacao:4.6,reviews:32,estoque:20},
{id:512,nome:"Polo Piquet Premium",categoria:"Camisetas",genero:"Masculino",preco:79.9,cores:["Branco","Preto","Marinho","Verde"],tamanhos:["P","M","G","GG"],emoji:"👕",descricao:"Polo piquet com gola estruturada e acabamento premium.",material:"Algodão piquet",avaliacao:4.8,reviews:67,estoque:29},
{id:513,nome:"Bolsa Mini Urban",categoria:"Acessórios",genero:"Feminino",preco:89.9,cores:["Preto","Caramelo","Off-white"],tamanhos:["Único"],emoji:"👜",tag:"NOVO",descricao:"Bolsa compacta com alça regulável e acabamento minimalista.",material:"Material sintético premium",avaliacao:4.7,reviews:28,estoque:13,novo:true},
{id:514,nome:"Boné Essential",categoria:"Acessórios",genero:"Unissex",preco:49.9,cores:["Preto","Bege","Azul"],tamanhos:["Único"],emoji:"🧢",descricao:"Boné ajustável para completar produções urbanas.",material:"Sarja de algodão",avaliacao:4.6,reviews:41,estoque:24},
{id:515,nome:"Vestido Curto Fresh",categoria:"Vestidos",genero:"Feminino",preco:89.9,cores:["Floral","Azul","Vermelho"],tamanhos:["P","M","G"],emoji:"👗",tag:"OFERTA",descricao:"Vestido curto leve para dias quentes e ocasiões descontraídas.",material:"Viscose",avaliacao:4.7,reviews:52,estoque:17},
{id:516,nome:"Camisa Linho Resort",categoria:"Camisas",genero:"Masculino",preco:119.9,cores:["Branco","Areia","Verde oliva"],tamanhos:["P","M","G","GG"],emoji:"👔",tag:"NOVO",descricao:"Camisa de visual resort com textura natural e modelagem confortável.",material:"Linho e viscose",avaliacao:4.8,reviews:36,estoque:15,novo:true}
];

export const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});