import Link from "next/link";
import {fashionProducts,money} from "./fashion-data";

const cats=[["👗","Feminino","Feminino"],["👔","Masculino","Masculino"],["✨","Novidades","Novidades"],["🔥","Ofertas","Promocoes"],["🏃","Fitness","Moda Fitness"],["👜","Acessórios","Acessórios"]];
export default function Home(){const destaques=fashionProducts.filter(p=>p.destaque).slice(0,4);return <main className="min-h-screen bg-[#f7f5f2] text-zinc-950 pb-28">
<header className="bg-white border-b border-zinc-200 px-5 py-4 sticky top-0 z-40"><div className="max-w-6xl mx-auto flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.3em] text-zinc-500">Fashion Store</p><h1 className="text-xl font-black tracking-tight">MODA.</h1></div><div className="flex gap-2"><Link href="/favoritos" className="w-11 h-11 grid place-items-center rounded-full border border-zinc-200">♡</Link><Link href="/carrinho" className="w-11 h-11 grid place-items-center rounded-full bg-black text-white">🛍️</Link></div></div></header>
<section className="max-w-6xl mx-auto px-5 pt-5"><div className="rounded-[32px] bg-zinc-950 text-white overflow-hidden min-h-[360px] grid md:grid-cols-2"><div className="p-7 md:p-10 flex flex-col justify-center"><p className="text-xs font-black uppercase tracking-[.24em] text-zinc-400">Nova coleção</p><h2 className="text-4xl md:text-6xl font-black leading-[.95] mt-3">Seu estilo.<br/>Do seu jeito.</h2><p className="text-zinc-300 mt-4 max-w-md">Descubra peças, monte looks, escolha cor e tamanho e compre em poucos toques.</p><div className="flex flex-wrap gap-3 mt-6"><Link href="/cardapio" className="bg-white text-black px-5 py-3 rounded-full font-black">Comprar agora</Link><Link href="/lookbook" className="border border-zinc-600 px-5 py-3 rounded-full font-bold">Ver looks</Link></div></div><div className="bg-gradient-to-br from-stone-200 via-neutral-300 to-zinc-400 min-h-[280px] flex items-center justify-center"><div className="text-[110px] md:text-[150px] drop-shadow-xl">🧥</div></div></div></section>
<section className="max-w-6xl mx-auto px-5 mt-6"><div className="bg-white border border-zinc-200 rounded-2xl px-4 py-3 flex gap-3 items-center"><span>🔎</span><Link href="/cardapio" className="text-zinc-500 flex-1">Buscar camiseta, vestido, jeans, cor...</Link><span className="text-xs font-bold bg-zinc-100 px-2 py-1 rounded-lg">📷 Busca visual</span></div></section>
<section className="max-w-6xl mx-auto px-5 mt-7"><div className="flex justify-between items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-zinc-500">Explore</p><h2 className="text-2xl font-black">Categorias</h2></div><Link href="/cardapio" className="text-sm font-bold">Ver tudo →</Link></div><div className="grid grid-cols-3 md:grid-cols-6 gap-3 mt-4">{cats.map(([icon,name,cat])=><Link key={name} href={`/cardapio?categoria=${encodeURIComponent(cat)}`} className="bg-white border border-zinc-200 rounded-2xl p-4 text-center"><div className="text-3xl">{icon}</div><p className="text-xs font-bold mt-2">{name}</p></Link>)}</div></section>
<section className="max-w-6xl mx-auto px-5 mt-8"><div className="flex justify-between items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-rose-600">Mais desejados</p><h2 className="text-2xl font-black">Destaques</h2></div><Link href="/cardapio" className="text-sm font-bold">Ver coleção →</Link></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4">{destaques.map(p=><Link href={`/cardapio?produto=${p.id}`} key={p.id} className="bg-white border border-zinc-200 rounded-3xl overflow-hidden"><div className="aspect-[4/5] bg-gradient-to-br from-stone-100 to-zinc-200 grid place-items-center text-7xl">{p.emoji}</div><div className="p-3"><p className="text-xs text-zinc-500">{p.categoria}</p><h3 className="font-bold text-sm mt-1 leading-tight min-h-[40px]">{p.nome}</h3><p className="font-black mt-2">{money(p.preco)}</p></div></Link>)}</div></section>
<section className="max-w-6xl mx-auto px-5 mt-8 grid md:grid-cols-3 gap-3"><Link href="/guia-tamanhos" className="bg-white border border-zinc-200 rounded-3xl p-5"><span className="text-3xl">📏</span><h3 className="font-black mt-3">Guia de tamanhos</h3><p className="text-sm text-zinc-500 mt-1">Ajude o cliente a escolher o tamanho certo.</p></Link><Link href="/favoritos" className="bg-white border border-zinc-200 rounded-3xl p-5"><span className="text-3xl">♡</span><h3 className="font-black mt-3">Favoritos</h3><p className="text-sm text-zinc-500 mt-1">Salve peças para decidir depois.</p></Link><Link href="/lookbook" className="bg-white border border-zinc-200 rounded-3xl p-5"><span className="text-3xl">✨</span><h3 className="font-black mt-3">Monte o look</h3><p className="text-sm text-zinc-500 mt-1">Inspirações e combinações prontas.</p></Link></section>
<section className="max-w-6xl mx-auto px-5 mt-8"><div className="bg-[#e9ded3] rounded-[32px] p-6 md:p-8"><p className="text-xs font-black uppercase tracking-[.18em]">Experiência moderna</p><h2 className="text-2xl font-black mt-2">Loja física + digital no mesmo app</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-5 text-sm font-semibold"><div>✓ Estoque por tamanho</div><div>✓ Aviso de reposição</div><div>✓ Avaliações</div><div>✓ Retirada na loja</div><div>✓ Cupons</div><div>✓ Histórico</div><div>✓ Compartilhar look</div><div>✓ Admin completo</div></div></div></section>
<footer className="max-w-6xl mx-auto px-5 py-8 text-center text-xs text-zinc-400">Protótipo de loja de roupas • dados demonstrativos</footer>
</main>}