import Link from "next/link";
import {produtosFarmacia} from "../data/farmacia";

const menus=[
 ["💊","Medicamentos","/cardapio"],["🌿","Saúde & Bem-estar","/cardapio"],["✨","Beleza & Higiene","/cardapio"],["📄","Receitas","/receitas"],
 ["🩺","Serviços","/servicos"],["📦","Meus pedidos","/historico"],["❤️","Favoritos","/favoritos"],["👤","Minha conta","/cadastro"]
];
const destaques=produtosFarmacia.filter(p=>!p.receita).slice(0,6);
const brl=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function Home(){return <main className="min-h-screen bg-slate-50 text-slate-900 pb-28">
<header className="bg-gradient-to-br from-sky-700 via-cyan-700 to-emerald-700 text-white px-5 pt-6 pb-7 rounded-b-[30px] shadow-sm"><div className="max-w-6xl mx-auto"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[.2em] text-cyan-100">Farmácia Demo</p><h1 className="text-3xl font-black mt-1">Farma Vida</h1><p className="text-sm text-cyan-100 mt-1">Cuidado, conveniência e saúde em um só app</p></div><Link href="/carrinho" className="bg-white text-sky-800 px-4 py-3 rounded-2xl font-black shadow">🛒 Sacola</Link></div><Link href="/cardapio" className="mt-5 bg-white/95 rounded-2xl px-4 py-3.5 text-slate-500 flex items-center gap-2 shadow"><span>🔎</span><span className="text-sm">Busque medicamento, vitamina, higiene...</span></Link></div></header>
<section className="px-5 mt-5 max-w-6xl mx-auto grid grid-cols-2 gap-3"><Link href="/receitas" className="col-span-2 bg-white border border-sky-100 rounded-3xl p-5 flex items-center justify-between gap-4 shadow-sm"><div><p className="text-xs font-black text-sky-700 uppercase">Comprar com receita</p><h2 className="text-2xl font-black mt-1">Envie sua prescrição</h2><p className="text-sm text-slate-500 mt-1">Foto, PDF ou token de receita digital para análise farmacêutica.</p></div><span className="text-5xl">📄</span></Link><Link href="/servicos" className="bg-emerald-50 border border-emerald-100 rounded-2xl p-4"><span className="text-2xl">💉</span><h3 className="font-black mt-2">Serviços</h3><p className="text-xs text-slate-500 mt-1">Vacinas, testes e cuidados</p></Link><Link href="/fidelidade" className="bg-amber-50 border border-amber-100 rounded-2xl p-4"><span className="text-2xl">⭐</span><h3 className="font-black mt-2">Clube Saúde</h3><p className="text-xs text-slate-500 mt-1">Descontos e benefícios</p></Link></section>
<section className="px-5 mt-7 max-w-6xl mx-auto"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Acesso rápido</h2><Link href="/cardapio" className="text-sm font-black text-sky-700">Ver catálogo</Link></div><div className="grid grid-cols-4 gap-3 mt-3">{menus.map(([icon,nome,href])=><Link href={href} key={nome} className="bg-white border border-slate-200 rounded-2xl p-3 text-center shadow-sm"><div className="text-2xl">{icon}</div><div className="text-[11px] font-bold mt-2 leading-tight">{nome}</div></Link>)}</div></section>
<section className="px-5 mt-7 max-w-6xl mx-auto"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-black text-emerald-700 uppercase">Seleção do dia</p><h2 className="text-xl font-black">Ofertas e cuidados</h2></div><Link href="/cardapio" className="text-sm font-black text-sky-700">Ver mais</Link></div><div className="grid grid-cols-2 md:grid-cols-3 gap-3 mt-3">{destaques.map(p=><article key={p.id} className="bg-white border border-slate-200 rounded-3xl p-3 shadow-sm"><div className="aspect-square rounded-2xl bg-gradient-to-br from-sky-50 to-emerald-50 flex items-center justify-center text-6xl">{p.emoji}</div><span className="inline-block mt-3 text-[9px] font-black px-2 py-1 rounded-full bg-sky-100 text-sky-700">{p.tag}</span><h3 className="font-bold text-sm mt-2 min-h-[40px] leading-tight">{p.nome}</h3><p className="text-xs text-slate-400 line-through mt-1">{brl(p.normal)}</p><p className="text-xl font-black text-sky-800">{brl(p.preco)}</p><p className="text-[11px] font-black text-amber-700 mt-1">⭐ Clube {brl(p.clube)}</p><Link href="/cardapio" className="block text-center bg-sky-700 text-white rounded-xl py-2.5 mt-3 font-black text-sm">Ver produto</Link></article>)}</div></section>
<section className="px-5 mt-7 max-w-6xl mx-auto grid md:grid-cols-3 gap-3"><div className="bg-white border border-slate-200 rounded-3xl p-5"><span className="text-3xl">⏰</span><h3 className="font-black mt-2">Lembretes de reposição</h3><p className="text-sm text-slate-500 mt-1">Base preparada para compras recorrentes e medicamentos de uso contínuo.</p></div><div className="bg-white border border-slate-200 rounded-3xl p-5"><span className="text-3xl">🏪</span><h3 className="font-black mt-2">Retirada na farmácia</h3><p className="text-sm text-slate-500 mt-1">Veja disponibilidade e escolha a unidade para retirada.</p></div><div className="bg-white border border-slate-200 rounded-3xl p-5"><span className="text-3xl">🧑‍⚕️</span><h3 className="font-black mt-2">Atendimento farmacêutico</h3><p className="text-sm text-slate-500 mt-1">Canal para orientação de uso e dúvidas sobre serviços.</p></div></section>
<section className="px-5 mt-7 max-w-6xl mx-auto"><div className="bg-slate-900 text-white rounded-3xl p-5"><p className="text-xs font-black text-cyan-300 uppercase">Segurança primeiro</p><h2 className="text-xl font-black mt-1">Medicamentos sujeitos a prescrição exigem validação</h2><p className="text-sm text-slate-300 mt-2">O app não substitui avaliação médica ou farmacêutica. Produtos com receita entram em fluxo específico de envio e conferência da prescrição antes da dispensação.</p></div></section>
<footer className="px-5 mt-8 max-w-6xl mx-auto text-center text-xs text-slate-400">Base demonstrativa de aplicativo para farmácias.</footer>
</main>}
