import Link from "next/link";
import {perfumeProducts,money} from "./perfume-data";

const cats=[["🌸","Femininos","Feminino"],["🌲","Masculinos","Masculino"],["✨","Unissex","Unissex"],["🎁","Kits para presente","Kits para presente"],["🧪","Descoberta","Discovery"],["🔥","Ofertas","Promoções"]];
const familias=[["🌹","Floral"],["🍋","Cítrico"],["🌲","Amadeirado"],["🌙","Oriental"],["🌿","Aromático"],["🍨","Gourmand"]];
export default function Home(){const destaques=perfumeProducts.filter(p=>p.destaque).slice(0,4);return <main className="min-h-screen bg-[#fbf8f5] text-[#231f20] pb-28">
<header className="bg-white border-b border-[#eadfd9] px-5 py-4"><div className="max-w-6xl mx-auto flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.28em] text-[#9a765f]">Perfumaria & Beleza</p><h1 className="text-xl font-black tracking-tight">ESSENZA.</h1></div><div className="flex gap-2"><Link href="/favoritos" className="w-11 h-11 grid place-items-center rounded-full border border-[#eadfd9]">♡</Link><Link href="/carrinho" className="w-11 h-11 grid place-items-center rounded-full bg-[#3a2628] text-white">🛍️</Link></div></div></header>
<section className="max-w-6xl mx-auto px-5 pt-5"><div className="rounded-[32px] bg-gradient-to-br from-[#3a2628] via-[#6b4547] to-[#b98975] text-white overflow-hidden min-h-[360px] grid md:grid-cols-2"><div className="p-7 md:p-10 flex flex-col justify-center"><p className="text-xs font-black uppercase tracking-[.24em] text-[#f1d9cd]">Descubra sua assinatura</p><h2 className="text-4xl md:text-6xl font-black leading-[.95] mt-3">Uma fragrância.<br/>Uma memória.</h2><p className="text-[#f4e7e1] mt-4 max-w-md">Explore perfumes por família olfativa, ocasião, intensidade e estilo.</p><div className="flex flex-wrap gap-3 mt-6"><Link href="/catalogo" className="bg-white text-[#3a2628] px-5 py-3 rounded-full font-black">Abrir catálogo</Link><Link href="/quiz-perfume" className="border border-white/40 px-5 py-3 rounded-full font-bold">Encontrar meu perfume</Link></div></div><div className="bg-gradient-to-br from-[#ead8cf] via-[#d8b8aa] to-[#b98875] min-h-[280px] flex items-center justify-center"><div className="text-[120px] md:text-[160px] drop-shadow-xl">🧴</div></div></div></section>
<section className="max-w-6xl mx-auto px-5 mt-6"><Link href="/catalogo" className="bg-white border border-[#eadfd9] rounded-2xl px-4 py-3 flex gap-3 items-center"><span>🔎</span><span className="text-[#876f64] flex-1">Buscar perfume, marca, família olfativa...</span><span className="text-xs font-bold bg-[#f6eee9] px-2 py-1 rounded-lg">Catálogo</span></Link></section>
<section className="max-w-6xl mx-auto px-5 mt-7"><div className="flex justify-between items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#9a765f]">Explore</p><h2 className="text-2xl font-black">Categorias</h2></div><Link href="/catalogo" className="text-sm font-bold">Ver tudo →</Link></div><div className="grid grid-cols-3 md:grid-cols-6 gap-3 mt-4">{cats.map(([icon,name,cat])=><Link key={name} href={`/catalogo?categoria=${encodeURIComponent(cat)}`} className="bg-white border border-[#eadfd9] rounded-2xl p-4 text-center"><div className="text-3xl">{icon}</div><p className="text-xs font-bold mt-2">{name}</p></Link>)}</div></section>
<section className="max-w-6xl mx-auto px-5 mt-8"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#9a765f]">Escolha pelo aroma</p><h2 className="text-2xl font-black">Famílias olfativas</h2></div><div className="grid grid-cols-3 md:grid-cols-6 gap-3 mt-4">{familias.map(([icon,nome])=><Link key={nome} href={`/catalogo?familia=${encodeURIComponent(nome)}`} className="rounded-2xl bg-[#f2e7e1] p-4 text-center"><div className="text-3xl">{icon}</div><p className="text-xs font-black mt-2">{nome}</p></Link>)}</div></section>
<section className="max-w-6xl mx-auto px-5 mt-8"><div className="flex justify-between items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#a34656]">Mais desejados</p><h2 className="text-2xl font-black">Destaques</h2></div><Link href="/catalogo" className="text-sm font-bold">Ver catálogo →</Link></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4">{destaques.map(p=><Link href={`/catalogo?produto=${p.id}`} key={p.id} className="bg-white border border-[#eadfd9] rounded-3xl overflow-hidden"><div className="aspect-square bg-gradient-to-br from-[#f6eee9] to-[#ead8cf] grid place-items-center text-7xl">{p.emoji}</div><div className="p-3"><p className="text-xs text-[#8b7268]">{p.marca} • {p.volume}</p><h3 className="font-bold text-sm mt-1 leading-tight min-h-[40px]">{p.nome}</h3><p className="font-black mt-2">{money(p.preco)}</p></div></Link>)}</div></section>
<section className="max-w-6xl mx-auto px-5 mt-8 grid md:grid-cols-3 gap-3"><Link href="/quiz-perfume" className="bg-white border border-[#eadfd9] rounded-3xl p-5"><span className="text-3xl">✨</span><h3 className="font-black mt-3">Encontre seu perfume</h3><p className="text-sm text-[#876f64] mt-1">Um quiz simples para sugerir famílias e estilos.</p></Link><Link href="/favoritos" className="bg-white border border-[#eadfd9] rounded-3xl p-5"><span className="text-3xl">♡</span><h3 className="font-black mt-3">Favoritos</h3><p className="text-sm text-[#876f64] mt-1">Salve fragrâncias para comparar depois.</p></Link><Link href="/catalogo?categoria=Kits%20para%20presente" className="bg-white border border-[#eadfd9] rounded-3xl p-5"><span className="text-3xl">🎁</span><h3 className="font-black mt-3">Presentes</h3><p className="text-sm text-[#876f64] mt-1">Kits e opções prontas para presentear.</p></Link></section>
<section className="max-w-6xl mx-auto px-5 mt-8"><div className="bg-[#ead8cf] rounded-[32px] p-6 md:p-8"><p className="text-xs font-black uppercase tracking-[.18em]">Experiência de perfumaria</p><h2 className="text-2xl font-black mt-2">Descoberta, comparação e compra no mesmo app</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-5 text-sm font-semibold"><div>✓ Famílias olfativas</div><div>✓ Notas de topo/coração/fundo</div><div>✓ Favoritos</div><div>✓ Avaliações</div><div>✓ Kits para presente</div><div>✓ Retirada na loja</div><div>✓ Cupons</div><div>✓ Admin completo</div></div></div></section>
<footer className="max-w-6xl mx-auto px-5 py-8 text-center text-xs text-[#a58f84]">Base de app para perfumaria • dados demonstrativos</footer>
<nav className="fixed bottom-0 left-0 right-0 bg-white border-t border-[#eadfd9] z-50"><div className="max-w-md mx-auto grid grid-cols-5 px-1 py-2"><Link href="/" className="text-center text-[#6b4547]"><div className="text-xl">⌂</div><span className="text-[10px] font-black">Início</span></Link><Link href="/catalogo" className="text-center text-[#8b7268]"><div className="text-xl">🧴</div><span className="text-[10px] font-bold">Catálogo</span></Link><Link href="/favoritos" className="text-center text-[#8b7268]"><div className="text-xl">♡</div><span className="text-[10px] font-bold">Favoritos</span></Link><Link href="/carrinho" className="text-center text-[#8b7268]"><div className="text-xl">🛍️</div><span className="text-[10px] font-bold">Sacola</span></Link><Link href="/cadastro" className="text-center text-[#8b7268]"><div className="text-xl">👤</div><span className="text-[10px] font-bold">Conta</span></Link></div></nav>
</main>}