export type PerfumeProduct={id:number;nome:string;marca:string;categoria:string;genero:"Feminino"|"Masculino"|"Unissex";familia:string;concentracao:string;volume:string;preco:number;precoAntigo?:number;emoji:string;tag?:string;descricao:string;notasTopo:string[];notasCoracao:string[];notasFundo:string[];avaliacao:number;reviews:number;estoque:number;novo?:boolean;destaque?:boolean};
export const perfumeCategories=["Todos","Novidades","Feminino","Masculino","Unissex","Importados","Nacionais","Kits para presente","Promoções"];
export const olfativas=["Floral","Cítrico","Amadeirado","Oriental","Aromático","Frutado","Fougère","Gourmand"];
export const perfumeProducts:PerfumeProduct[]=[
{id:801,nome:"Essenza Rouge",marca:"Maison Lumière",categoria:"Importados",genero:"Feminino",familia:"Floral",concentracao:"Eau de Parfum",volume:"100 ml",preco:389.9,precoAntigo:449.9,emoji:"🌹",tag:"DESTAQUE",descricao:"Fragrância floral elegante, intensa e sofisticada.",notasTopo:["Bergamota","Pera"],notasCoracao:["Rosa","Jasmim"],notasFundo:["Baunilha","Patchouli"],avaliacao:4.9,reviews:128,estoque:18,destaque:true},
{id:802,nome:"Blue Horizon",marca:"Atlas",categoria:"Importados",genero:"Masculino",familia:"Aromático",concentracao:"Eau de Toilette",volume:"100 ml",preco:329.9,emoji:"🌊",tag:"MAIS VENDIDO",descricao:"Fresco e aromático para o dia a dia.",notasTopo:["Limão","Menta"],notasCoracao:["Lavanda","Gerânio"],notasFundo:["Cedro","Âmbar"],avaliacao:4.8,reviews:201,estoque:27,destaque:true},
{id:803,nome:"Velvet Oud",marca:"Noir Maison",categoria:"Importados",genero:"Unissex",familia:"Oriental",concentracao:"Eau de Parfum",volume:"80 ml",preco:459.9,emoji:"🖤",tag:"PREMIUM",descricao:"Oud envolvente com especiarias e madeiras nobres.",notasTopo:["Açafrão","Pimenta rosa"],notasCoracao:["Oud","Rosa"],notasFundo:["Âmbar","Sândalo"],avaliacao:4.9,reviews:94,estoque:9,destaque:true},
{id:804,nome:"Citrus Bloom",marca:"Viva",categoria:"Nacionais",genero:"Feminino",familia:"Cítrico",concentracao:"Colônia",volume:"100 ml",preco:129.9,emoji:"🍋",tag:"NOVO",descricao:"Leve, luminoso e refrescante.",notasTopo:["Limão siciliano","Mandarina"],notasCoracao:["Flor de laranjeira"],notasFundo:["Almíscar branco"],avaliacao:4.7,reviews:76,estoque:34,novo:true},
{id:805,nome:"Urban Wood",marca:"Element",categoria:"Nacionais",genero:"Masculino",familia:"Amadeirado",concentracao:"Eau de Parfum",volume:"100 ml",preco:179.9,precoAntigo:199.9,emoji:"🌲",tag:"OFERTA",descricao:"Amadeirado moderno com assinatura marcante.",notasTopo:["Bergamota"],notasCoracao:["Vetiver","Cedro"],notasFundo:["Couro","Âmbar"],avaliacao:4.8,reviews:112,estoque:22,destaque:true},
{id:806,nome:"Vanilla Kiss",marca:"Lumi",categoria:"Nacionais",genero:"Feminino",familia:"Gourmand",concentracao:"Eau de Parfum",volume:"75 ml",preco:159.9,emoji:"🍨",tag:"QUERIDINHO",descricao:"Doce na medida, cremoso e confortável.",notasTopo:["Pera"],notasCoracao:["Caramelo","Flor branca"],notasFundo:["Baunilha","Fava tonka"],avaliacao:4.9,reviews:167,estoque:31},
{id:807,nome:"Green Pulse",marca:"Natura Lab",categoria:"Nacionais",genero:"Unissex",familia:"Cítrico",concentracao:"Eau de Toilette",volume:"100 ml",preco:149.9,emoji:"🌿",descricao:"Verde, cítrico e energizante.",notasTopo:["Limão","Folhas verdes"],notasCoracao:["Chá verde"],notasFundo:["Musk"],avaliacao:4.6,reviews:59,estoque:16,novo:true},
{id:808,nome:"Gift Duo Romance",marca:"Maison Lumière",categoria:"Kits para presente",genero:"Feminino",familia:"Floral",concentracao:"Kit",volume:"2 itens",preco:419.9,emoji:"🎁",tag:"PRESENTE",descricao:"Kit especial com perfume e loção corporal.",notasTopo:["Pera"],notasCoracao:["Rosa"],notasFundo:["Baunilha"],avaliacao:4.8,reviews:43,estoque:12},
{id:809,nome:"Midnight Amber",marca:"Noir Maison",categoria:"Importados",genero:"Unissex",familia:"Oriental",concentracao:"Parfum",volume:"50 ml",preco:529.9,emoji:"✨",descricao:"Intenso, quente e sofisticado para a noite.",notasTopo:["Canela"],notasCoracao:["Âmbar"],notasFundo:["Baunilha","Madeiras"],avaliacao:4.9,reviews:88,estoque:7},
{id:810,nome:"Fresh Sport",marca:"Atlas",categoria:"Importados",genero:"Masculino",familia:"Aromático",concentracao:"Eau de Toilette",volume:"100 ml",preco:299.9,emoji:"⚡",tag:"NOVO",descricao:"Aromático fresco com sensação limpa e esportiva.",notasTopo:["Toranja"],notasCoracao:["Lavanda"],notasFundo:["Vetiver"],avaliacao:4.7,reviews:69,estoque:20,novo:true},
{id:811,nome:"Peony Dream",marca:"Viva",categoria:"Nacionais",genero:"Feminino",familia:"Floral",concentracao:"Eau de Parfum",volume:"90 ml",preco:189.9,emoji:"🌸",descricao:"Floral delicado, romântico e confortável.",notasTopo:["Frutas vermelhas"],notasCoracao:["Peônia","Rosa"],notasFundo:["Musk"],avaliacao:4.8,reviews:91,estoque:24},
{id:812,nome:"Discovery Set 6 Fragrâncias",marca:"Seleção",categoria:"Kits para presente",genero:"Unissex",familia:"Aromático",concentracao:"Miniaturas",volume:"6 x 5 ml",preco:119.9,emoji:"🧪",tag:"DESCUBRA",descricao:"Kit de miniaturas para experimentar diferentes famílias olfativas.",notasTopo:["Variadas"],notasCoracao:["Variadas"],notasFundo:["Variadas"],avaliacao:4.9,reviews:55,estoque:28}
];
export const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});