"use client";

import Link from "next/link";
import {useMemo,useState} from "react";
import {useCart} from "../context/CartContext";
import {categoriasFarmacia,produtosFarmacia} from "../../data/farmacia";

const brl=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function CatalogoFarmacia(){
 const {adicionar,quantidadeTotal,total}=useCart();
 const [busca,setBusca]=useState("");const[categoria,setCategoria]=useState("Todos");const[somenteOfertas,setSomenteOfertas]=useState(false);const[toast,setToast]=useState("");
 const q=busca.trim().toLowerCase();
 const lista=useMemo(()=>produtosFarmacia.filter(p=>(categoria==="Todos"||p.categoria===categoria)&&(!q||`${p.nome} ${p.categoria} ${p.marca||""}`.toLowerCase().includes(q))&&(!somenteOfertas||p.normal>p.preco)),[categoria,q,somenteOfertas]);
 function add(p:(typeof produtosFarmacia)[number]){if(p.receita)return;adicionar({id:p.id,nome:p.nome,preco:p.preco});setToast(`✓ ${p.nome} adicionado`);setTimeout(()=>setToast(""),1300)}
 return <main className="min-h-screen bg-slate-50 text-slate-900 pb-36"><header className="bg-sky-700 text-white px-4 py-5"><div className="max-w-6xl mx-auto"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-sky-100">Farma Vida</p><h1 className="text-2xl font-black">Medicamentos e cuidados</h1></div><Link href="/carrinho" className="bg-white text-sky-800 rounded-2xl px-4 py-3 font-black">🛒 {quantidadeTotal}</Link></div><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="🔎 Buscar medicamento, vitamina, higiene..." className="w-full mt-4 rounded-2xl px-4 py-3 text-slate-900 outline-none"/></div></header>
 <div className="max-w-6xl mx-auto px-4"><div className="flex gap-2 overflow-x-auto py-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{categoriasFarmacia.map(c=><button key={c} onClick={()=>setCategoria(c)} className={`whitespace-nowrap px-4 py-2.5 rounded-full text-sm font-black ${categoria===c?"bg-sky-700 text-white":"bg-white border border-slate-200"}`}>{c}</button>)}</div><div className="flex items-center justify-between mb-4"><div><p className="text-xs font-black text-sky-700 uppercase">{lista.length} produtos</p><h2 className="text-xl font-black">{categoria}</h2></div><label className="flex items-center gap-2 bg-white border border-slate-200 rounded-xl px-3 py-2 text-sm font-bold"><input type="checkbox" checked={somenteOfertas} onChange={e=>setSomenteOfertas(e.target.checked)}/> Só ofertas</label></div>
 <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">{lista.map(p=><article key={p.id} className="bg-white border border-slate-200 rounded-3xl overflow-hidden shadow-sm"><div className="aspect-square bg-gradient-to-br from-sky-50 to-emerald-50 flex items-center justify-center text-6xl relative"><span>{p.emoji}</span><span className={`absolute top-2 left-2 text-white text-[9px] font-black px-2 py-1 rounded-full ${p.receita?"bg-rose-600":"bg-sky-700"}`}>{p.tag}</span></div><div className="p-3"><p className="text-xs font-bold text-slate-400">{p.categoria}{p.marca?` • ${p.marca}`:""}</p><h3 className="font-black text-sm mt-1 min-h-[44px] leading-tight">{p.nome}</h3><p className="text-xs line-through text-slate-400 mt-2">{brl(p.normal)}</p><p className="text-xl font-black text-sky-800 leading-none">{brl(p.preco)}</p><p className="text-[11px] font-black text-amber-700 mt-1">⭐ Clube {brl(p.clube)}</p><p className="text-[10px] text-slate-400 mt-1">Estoque demo: {p.estoque}</p>{p.receita?<Link href="/receitas" className="block text-center w-full bg-rose-600 text-white rounded-xl py-3 mt-3 font-black text-sm">Enviar receita</Link>:<button onClick={()=>add(p)} className="w-full bg-sky-700 text-white rounded-xl py-3 mt-3 font-black">Adicionar</button>}{p.controlado&&<p className="text-[10px] text-rose-600 font-bold mt-2">Dispensação somente após validação farmacêutica e conforme legislação aplicável.</p>}</div></article>)}</div>
 {!lista.length&&<div className="bg-white border border-slate-200 rounded-3xl p-8 text-center mt-4"><div className="text-4xl">🔎</div><h3 className="font-black mt-2">Nada encontrado</h3><p className="text-sm text-slate-500 mt-1">Tente outro nome ou categoria.</p></div>}</div>
 {quantidadeTotal>0&&<Link href="/carrinho" className="fixed bottom-4 left-4 right-4 max-w-xl mx-auto bg-slate-950 text-white rounded-2xl p-4 flex items-center justify-between shadow-2xl z-50"><div><b>{quantidadeTotal} {quantidadeTotal===1?"item":"itens"}</b><p className="text-xs text-slate-400">Ir para a sacola</p></div><b className="text-cyan-300">{brl(total)} →</b></Link>}{toast&&<div className="fixed top-4 left-1/2 -translate-x-1/2 z-[80] bg-slate-950 text-white px-4 py-3 rounded-xl shadow-xl text-sm font-bold">{toast}</div>}
 </main>
}
