"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {useCart} from "../context/CartContext";
import {formatPrice} from "../../utils/format";

export default function Checkout(){
 const {items,total,limpar}=useCart();const[tipo,setTipo]=useState<"entrega"|"retirada">("entrega");const[pagamento,setPagamento]=useState("Pix");const[endereco,setEndereco]=useState("");const[nome,setNome]=useState("");const[tel,setTel]=useState("");const[slot,setSlot]=useState("Hoje • 18h–20h");const[cupom,setCupom]=useState("");const[desconto,setDesconto]=useState(0);const[ok,setOk]=useState(false);const frete=tipo==="entrega"?7.9:0;const totalFinal=useMemo(()=>Math.max(0,total+frete-desconto),[total,frete,desconto]);
 function aplicar(){const c=cupom.trim().toUpperCase();setDesconto(c==="FARMA10"?Math.min(total*.1,25):0)}
 function finalizar(){if(!items.length||!nome.trim()||!tel.trim()||(tipo==="entrega"&&!endereco.trim()))return;setOk(true);limpar()}
 if(ok)return <main className="min-h-screen bg-slate-50 p-5 text-slate-900"><div className="max-w-md mx-auto bg-white rounded-3xl p-7 text-center border border-slate-200 mt-10"><div className="text-6xl">✅</div><h1 className="text-3xl font-black mt-3">Pedido confirmado</h1><p className="text-slate-500 mt-2">Pedido demonstrativo concluído. Itens sujeitos a prescrição continuam dependendo de validação farmacêutica.</p><Link href="/cardapio" className="block bg-sky-700 text-white py-4 rounded-2xl font-black mt-5">Voltar ao catálogo</Link></div></main>;
 return <main className="min-h-screen bg-slate-50 text-slate-900 p-4 pb-28"><div className="max-w-3xl mx-auto"><div className="flex items-center justify-between"><div><p className="text-xs font-black text-sky-700 uppercase">Farma Vida</p><h1 className="text-3xl font-black">Finalizar compra</h1></div><Link href="/carrinho" className="text-sm font-bold text-sky-700">← Sacola</Link></div>
 <section className="mt-5 bg-white border border-slate-200 rounded-3xl p-5"><h2 className="font-black text-lg">Como quer receber?</h2><div className="grid grid-cols-2 gap-2 mt-3"><button onClick={()=>setTipo("entrega")} className={`p-4 rounded-2xl font-black ${tipo==="entrega"?"bg-sky-700 text-white":"bg-slate-100"}`}>🚚 Entrega</button><button onClick={()=>setTipo("retirada")} className={`p-4 rounded-2xl font-black ${tipo==="retirada"?"bg-sky-700 text-white":"bg-slate-100"}`}>🏪 Retirada</button></div>{tipo==="entrega"&&<input value={endereco} onChange={e=>setEndereco(e.target.value)} placeholder="Rua, nº, bairro e referência" className="w-full mt-3 bg-slate-100 border border-slate-200 rounded-xl p-3"/>}<select value={slot} onChange={e=>setSlot(e.target.value)} className="w-full mt-3 bg-slate-100 border border-slate-200 rounded-xl p-3"><option>Hoje • 18h–20h</option><option>Hoje • 20h–22h</option><option>Amanhã • 8h–10h</option><option>Amanhã • 10h–12h</option></select></section>
 <section className="mt-4 bg-white border border-slate-200 rounded-3xl p-5 space-y-3"><h2 className="font-black text-lg">Seus dados</h2><input value={nome} onChange={e=>setNome(e.target.value)} placeholder="Nome" className="w-full bg-slate-100 border border-slate-200 rounded-xl p-3"/><input value={tel} onChange={e=>setTel(e.target.value)} placeholder="WhatsApp" className="w-full bg-slate-100 border border-slate-200 rounded-xl p-3"/><select value={pagamento} onChange={e=>setPagamento(e.target.value)} className="w-full bg-slate-100 border border-slate-200 rounded-xl p-3"><option>Pix</option><option>Cartão</option><option>Dinheiro</option></select></section>
 <section className="mt-4 bg-rose-50 border border-rose-100 rounded-3xl p-5"><h2 className="font-black text-rose-800">📄 Tem item com receita?</h2><p className="text-sm text-rose-700 mt-2">Faça o envio em Receitas. O farmacêutico precisa validar a prescrição antes da dispensação.</p><Link href="/receitas" className="inline-block mt-3 font-black text-rose-800">Ir para Receitas →</Link></section>
 <section className="mt-4 bg-white border border-slate-200 rounded-3xl p-5"><h2 className="font-black">Cupom</h2><div className="flex gap-2 mt-3"><input value={cupom} onChange={e=>setCupom(e.target.value)} placeholder="Ex.: FARMA10" className="flex-1 bg-slate-100 border border-slate-200 rounded-xl p-3"/><button onClick={aplicar} className="bg-slate-900 text-white px-4 rounded-xl font-black">Aplicar</button></div></section>
 <section className="mt-4 bg-white border border-slate-200 rounded-3xl p-5"><div className="flex justify-between text-sm"><span>Produtos</span><b>{formatPrice(total)}</b></div><div className="flex justify-between text-sm mt-2"><span>{tipo==="entrega"?"Entrega":"Retirada"}</span><b>{formatPrice(frete)}</b></div>{desconto>0&&<div className="flex justify-between text-sm mt-2 text-emerald-700"><span>Desconto</span><b>- {formatPrice(desconto)}</b></div>}<div className="flex justify-between text-xl font-black mt-4 pt-4 border-t"><span>Total</span><span className="text-sky-800">{formatPrice(totalFinal)}</span></div><button onClick={finalizar} disabled={!items.length} className="w-full mt-4 bg-sky-700 disabled:bg-slate-300 text-white py-4 rounded-2xl font-black">Confirmar pedido</button></section></div></main>
}
