"use client";
import { useEffect, useState } from "react";
const META=10;

type Cliente={nome?:string;telefone:string;pontos:number;total_pedidos?:number;total_gasto?:number};
export default function Fidelidade(){
 const [telefone,setTelefone]=useState("");const [selos,setSelos]=useState(0);const [carregado,setCarregado]=useState(false);const [salvando,setSalvando]=useState(false);const [status,setStatus]=useState("");
 async function consultar(t:string){const tel=t.replace(/\D/g,"");if(tel.length<10)return;try{const r=await fetch(`/api/fidelidade?telefone=${encodeURIComponent(tel)}`,{cache:"no-store"});const j=await r.json();if(r.ok&&j.cliente){setSelos(Number(j.cliente.pontos||0));setStatus("Cartão sincronizado com a Popular.")}else if(r.ok){setSelos(0);setStatus("WhatsApp ainda não cadastrado no Clube Popular.")}}catch{setStatus("Não foi possível sincronizar agora.")}}
 useEffect(()=>{const t=localStorage.getItem("popular-fidelidade-telefone")||"";setTelefone(t);setCarregado(true);if(t)void consultar(t)},[]);
 async function salvar(){const tel=telefone.replace(/\D/g,"");if(tel.length<10){alert("Digite um WhatsApp válido com DDD.");return}setSalvando(true);setStatus("");try{const r=await fetch("/api/fidelidade",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({telefone:tel})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Erro");localStorage.setItem("popular-fidelidade-telefone",tel);setTelefone(tel);setSelos(Number(j.cliente?.pontos||0));setStatus(j.criado?"Cartão criado e salvo com segurança!":"Cartão encontrado e sincronizado!")}catch{setStatus("Não foi possível salvar. Tente novamente.")}finally{setSalvando(false)}}
 function solicitar(){if(!telefone){alert("Cadastre seu WhatsApp primeiro.");return}const msg=`⭐ *FIDELIDADE POPULAR*\n\nOlá! Meu WhatsApp cadastrado é ${telefone}.\nGostaria de validar minha compra e receber meu selo no programa de fidelidade.`;window.open(`https://wa.me/5538991429166?text=${encodeURIComponent(msg)}`,"_blank")}
 function resgatar(){const msg=`🎁 *RESGATE FIDELIDADE POPULAR*\n\nOlá! Completei ${META} selos no meu cartão fidelidade e gostaria de solicitar minha recompensa.\nWhatsApp cadastrado: ${telefone}`;window.open(`https://wa.me/5538991429166?text=${encodeURIComponent(msg)}`,"_blank")}
 if(!carregado)return <main className="min-h-screen bg-zinc-950"/>;
 const faltam=Math.max(META-selos,0);const progresso=Math.min((selos/META)*100,100);
 return <main className="min-h-screen bg-zinc-950 text-white p-4 pb-28 max-w-2xl mx-auto"><header className="pt-3"><p className="text-yellow-400 font-bold text-sm">POPULAR HAMBURGUERIA E SORVETERIA</p><h1 className="text-3xl font-black mt-1">⭐ Clube Popular</h1><p className="text-zinc-400 mt-2">Seu cartão fidelidade digital, agora sincronizado com a Popular.</p></header>
 <section className="mt-6 bg-gradient-to-br from-yellow-400 to-yellow-500 text-black rounded-3xl p-6 shadow-xl"><div className="flex justify-between"><div><p className="font-bold opacity-70">SEU CARTÃO</p><h2 className="text-3xl font-black mt-1">{selos}/{META} selos</h2></div><div className="text-4xl">🍔</div></div><div className="grid grid-cols-5 gap-3 mt-6">{Array.from({length:META}).map((_,i)=><div key={i} className={`aspect-square rounded-full flex items-center justify-center text-xl border-2 border-black/20 ${i<selos?"bg-black text-yellow-400":"bg-white/35"}`}>{i<selos?"★":i+1}</div>)}</div><div className="h-3 bg-black/20 rounded-full mt-6 overflow-hidden"><div className="h-full bg-black rounded-full transition-all" style={{width:`${progresso}%`}}/></div><p className="font-bold mt-3">{faltam>0?`Faltam ${faltam} selo${faltam===1?"":"s"} para completar seu cartão.`:"🎉 Cartão completo! Sua recompensa está disponível."}</p></section>
 <section className="mt-5 bg-zinc-900 border border-zinc-800 rounded-3xl p-5"><h2 className="text-xl font-black">🎁 Recompensa</h2><p className="text-zinc-300 mt-2">Complete {META} selos e solicite sua recompensa na Popular.</p>{selos>=META&&<button onClick={resgatar} className="w-full mt-4 bg-green-500 text-black py-3 rounded-xl font-black">Solicitar recompensa pelo WhatsApp</button>}</section>
 <section className="mt-5 bg-zinc-900 border border-zinc-800 rounded-3xl p-5"><h2 className="text-xl font-black">📱 Identificação</h2><p className="text-zinc-400 text-sm mt-1">Use o mesmo WhatsApp dos seus pedidos. Seus selos ficam salvos no sistema da Popular.</p><input value={telefone} onChange={e=>setTelefone(e.target.value)} placeholder="(38) 99999-9999" inputMode="tel" className="w-full mt-4 bg-zinc-800 border border-zinc-700 rounded-xl p-3 outline-none focus:border-yellow-400"/><button disabled={salvando} onClick={salvar} className="w-full mt-3 bg-yellow-400 disabled:opacity-60 text-black py-3 rounded-xl font-black">{salvando?"Sincronizando...":"Salvar e sincronizar meu cartão"}</button>{status&&<p className="text-sm text-zinc-300 mt-3">{status}</p>}</section>
 <section className="mt-5 bg-zinc-900 border border-zinc-800 rounded-3xl p-5"><h2 className="text-xl font-black">Como ganhar selos?</h2><p className="text-zinc-400 text-sm mt-2">Após uma compra válida, solicite a validação à Popular. A equipe confirma o pedido antes de creditar o selo, evitando créditos indevidos.</p><button onClick={solicitar} className="w-full mt-4 border border-yellow-400 text-yellow-400 py-3 rounded-xl font-black">Solicitar validação da compra</button></section>
 <details className="mt-5 bg-zinc-900 border border-zinc-800 rounded-3xl p-5"><summary className="font-black cursor-pointer">ℹ️ Regras do programa</summary><div className="text-sm text-zinc-400 mt-3 space-y-2"><p>• O selo só é liberado após confirmação de uma compra válida.</p><p>• O saldo fica vinculado ao WhatsApp cadastrado e salvo no sistema da Popular.</p><p>• A recompensa é confirmada pela Popular antes do resgate.</p><p>• A Popular pode definir quais compras são elegíveis e atualizar as regras do programa.</p></div></details>
 </main>;
}
