"use client";
import Link from "next/link";
import {useState} from "react";

export default function Receitas(){const[modo,setModo]=useState("foto");const[token,setToken]=useState("");const[nome,setNome]=useState("");const[status,setStatus]=useState("");function enviar(){if(!nome.trim())return;setStatus("Receita enviada para análise farmacêutica no protótipo.")}
return <main className="min-h-screen bg-slate-50 text-slate-900 p-4 pb-24"><div className="max-w-2xl mx-auto"><div className="flex items-center justify-between"><div><p className="text-xs font-black text-sky-700 uppercase">Farma Vida</p><h1 className="text-3xl font-black">Minhas receitas</h1><p className="text-sm text-slate-500 mt-1">Envie sua prescrição para conferência.</p></div><Link href="/" className="text-sm font-black text-sky-700">Início</Link></div>
<section className="mt-5 bg-white border border-slate-200 rounded-3xl p-5"><h2 className="font-black text-lg">Como deseja enviar?</h2><div className="grid grid-cols-3 gap-2 mt-3"><button onClick={()=>setModo("foto")} className={`p-3 rounded-2xl font-black text-sm ${modo==="foto"?"bg-sky-700 text-white":"bg-slate-100"}`}>📷 Foto</button><button onClick={()=>setModo("arquivo")} className={`p-3 rounded-2xl font-black text-sm ${modo==="arquivo"?"bg-sky-700 text-white":"bg-slate-100"}`}>📎 PDF</button><button onClick={()=>setModo("token")} className={`p-3 rounded-2xl font-black text-sm ${modo==="token"?"bg-sky-700 text-white":"bg-slate-100"}`}>🔑 Token</button></div>{modo==="token"?<input value={token} onChange={e=>setToken(e.target.value)} placeholder="Token da receita digital" className="w-full mt-4 bg-slate-100 border border-slate-200 rounded-xl p-3"/>:<div className="mt-4 border-2 border-dashed border-slate-300 rounded-2xl p-8 text-center text-slate-500"><div className="text-4xl">{modo==="foto"?"📷":"📎"}</div><p className="font-bold mt-2">Área de upload demonstrativa</p><p className="text-xs mt-1">Na versão conectada, o cliente poderá tirar foto ou anexar PDF.</p></div>}<input value={nome} onChange={e=>setNome(e.target.value)} placeholder="Nome do paciente" className="w-full mt-4 bg-slate-100 border border-slate-200 rounded-xl p-3"/><button onClick={enviar} className="w-full mt-3 bg-sky-700 text-white rounded-2xl py-4 font-black">Enviar para análise</button>{status&&<div className="mt-3 bg-emerald-50 border border-emerald-100 text-emerald-800 rounded-xl p-3 font-bold text-sm">✓ {status}</div>}</section>
<section className="mt-4 bg-amber-50 border border-amber-100 rounded-3xl p-5"><h2 className="font-black text-amber-900">Importante</h2><p className="text-sm text-amber-800 mt-2">Receitas precisam estar legíveis e completas. Medicamentos sujeitos a controle especial podem exigir retenção da receita ou outros procedimentos conforme a legislação e validação do farmacêutico.</p></section>
<section className="mt-4 grid grid-cols-2 gap-3"><div className="bg-white border border-slate-200 rounded-2xl p-4"><span className="text-2xl">🕘</span><h3 className="font-black mt-2">Histórico</h3><p className="text-xs text-slate-500 mt-1">Receitas enviadas e validade.</p></div><div className="bg-white border border-slate-200 rounded-2xl p-4"><span className="text-2xl">🧑‍⚕️</span><h3 className="font-black mt-2">Farmacêutico</h3><p className="text-xs text-slate-500 mt-1">Status da análise e orientação.</p></div></section></div></main>}
