"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import Operacao from "../Operacao";
const KEY="popular_admin_token";
export default function OperacoesPage(){
 const[token,setToken]=useState("");const[d,setD]=useState<any>({pedidos:[],premios:[],aniversarios:[]});const[func,setFunc]=useState("");const[msg,setMsg]=useState("");const[loading,setLoading]=useState(true);const[expirada,setExpirada]=useState(false);
 useEffect(()=>{setToken(localStorage.getItem(KEY)||"");setFunc(localStorage.getItem("popular_admin_funcionario")||"")},[]);
 const api=useCallback(async(body:any)=>{try{const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(body)}),j=await r.json();if(r.status===401||String(j.error||"").toLowerCase().includes("sessão")||String(j.error||"").toLowerCase().includes("sessao")){localStorage.removeItem(KEY);setToken("");setExpirada(true);setMsg("");return null}if(!r.ok){setMsg(`⚠️ ${j.error||"Erro na operação"}`);return null}return j}catch{setMsg("⚠️ Falha de conexão. Tente novamente.");return null}},[token]);
 const load=useCallback(async()=>{if(!token)return;setLoading(true);const [po,pr,an]=await Promise.all([api({action:"listar_pedidos"}),api({action:"listar_premios"}),api({action:"listar_aniversarios_pendentes"})]);if(po||pr||an)setD({pedidos:po?.pedidos||[],premios:pr?.premios||[],aniversarios:an?.clientes||an?.aniversarios||[]});setLoading(false)},[token,api]);
 useEffect(()=>{if(!token)return;void load();const x=setInterval(()=>void load(),15000);return()=>clearInterval(x)},[token,load]);
 if(!token)return <main className="min-h-screen bg-zinc-950 text-white grid place-items-center p-5"><div className="max-w-sm w-full bg-zinc-900 border border-zinc-800 rounded-3xl p-7 text-center"><div className="text-6xl">🔐</div><h1 className="text-2xl font-black mt-3">{expirada?"Sua sessão expirou":"Operações protegidas"}</h1><p className="text-zinc-400 mt-2">{expirada?"Por segurança, entre novamente no Painel Admin para continuar.":"Entre no Painel Admin primeiro para acessar pedidos, prêmios e aniversários."}</p><Link href="/admin" className="block bg-yellow-400 text-black p-4 rounded-xl font-black mt-5">🔑 {expirada?"Entrar novamente":"Entrar no Admin"}</Link></div></main>;
 return <main className="min-h-screen bg-zinc-950 text-white p-4 pb-24"><div className="max-w-4xl mx-auto"><header className="flex justify-between items-center gap-3"><div><p className="text-yellow-400 text-xs font-black">POPULAR • CENTRAL DE GESTÃO</p><h1 className="text-3xl font-black">⚡ Operações</h1><p className="text-zinc-500 text-sm mt-1">Pedidos, fidelidade e conferências em um só lugar.</p></div><Link href="/admin" className="bg-zinc-800 px-4 py-3 rounded-xl font-bold">← Admin</Link></header>{msg&&<div className="mt-4 bg-zinc-800 border border-zinc-700 p-3 rounded-xl text-sm text-center">{msg}</div>}{loading?<div className="mt-8 bg-zinc-900 rounded-3xl p-8 text-center"><div className="animate-pulse text-4xl">⚡</div><p className="text-zinc-400 mt-3">Carregando central operacional...</p></div>:<Operacao d={d} api={api} load={load} func={func} setFunc={setFunc} setMsg={setMsg}/>}</div></main>
}
