"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
const KEY="popular_admin_token";
export default function Entregas(){
 const[token,setToken]=useState("");const[pedidos,setPedidos]=useState<any[]>([]);const[msg,setMsg]=useState("");const[busy,setBusy]=useState("");
 useEffect(()=>{const t=localStorage.getItem(KEY)||"";setToken(t);if(t)void carregar(t)},[]);
 async function api(body:any,t=token){const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error||"Erro");return j}
 async function carregar(t=token){try{const j=await api({action:"listar_pedidos"},t);setPedidos(j.pedidos||[]);setMsg("")}catch(e:any){setMsg(e.message||"Não foi possível carregar.")}}
 async function entregar(p:any){if(!confirm(`Confirmar que o pedido ${p.pedido_id} foi entregue?`))return;setBusy(p.pedido_id);try{const j=await api({action:"confirmar_entrega",pedido_id:p.pedido_id});setPedidos(x=>x.filter(y=>y.pedido_id!==p.pedido_id));setMsg("✅ Entrega confirmada. Abrindo WhatsApp do cliente...");if(j.telefone){const f=String(j.telefone).replace(/\D/g,"");const n=f.startsWith("55")?f:`55${f}`;window.open(`https://wa.me/${n}?text=${encodeURIComponent(j.mensagem)}`,"_blank")}}catch(e:any){setMsg(e.message||"Não foi possível confirmar.")}finally{setBusy("")}}
 if(!token)return <main className="min-h-screen bg-zinc-950 text-white p-6 grid place-items-center"><div className="bg-zinc-900 p-6 rounded-3xl max-w-sm text-center"><div className="text-5xl">🔐</div><h1 className="text-2xl font-black mt-3">Acesso administrativo</h1><p className="text-zinc-400 mt-2">Entre primeiro no Painel Admin.</p><Link href="/admin" className="block bg-yellow-400 text-black p-4 rounded-xl font-black mt-5">Ir para o Admin</Link></div></main>;
 return <main className="min-h-screen bg-zinc-950 text-white p-4 pb-24"><div className="max-w-3xl mx-auto"><header className="flex items-center justify-between gap-3"><div><p className="text-yellow-400 text-xs font-black">POPULAR • OPERAÇÃO</p><h1 className="text-3xl font-black">🛵 Entregas</h1></div><Link href="/admin" className="bg-zinc-800 px-4 py-3 rounded-xl font-bold">← Admin</Link></header><div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4 mt-5"><div className="flex justify-between items-center"><div><b>Pedidos aguardando finalização</b><p className="text-xs text-zinc-400">Confirme somente depois da entrega real.</p></div><button onClick={()=>carregar()} className="bg-zinc-800 px-3 py-2 rounded-xl">↻</button></div></div>{pedidos.length===0?<div className="bg-zinc-900 rounded-2xl p-8 text-center mt-4"><div className="text-5xl">✅</div><b className="block mt-3">Nenhuma entrega pendente</b></div>:<div className="space-y-3 mt-4">{pedidos.map(p=><article key={p.pedido_id} className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4"><div className="flex justify-between gap-3"><div><b className="text-lg">{p.nome_cliente||"Cliente"}</b><p className="text-xs text-zinc-500">{p.pedido_id}</p><p className="text-sm text-zinc-300 mt-2">📱 {p.whatsapp}</p>{p.endereco_entrega&&<p className="text-sm text-zinc-300">📍 {p.endereco_entrega}</p>}</div><b className="text-yellow-400">R$ {Number(p.total||0).toFixed(2).replace(".",",")}</b></div><details className="bg-zinc-950 rounded-xl p-3 mt-3"><summary className="font-bold">🍔 Ver pedido</summary>{(p.itens||[]).map((i:any,n:number)=><p key={n} className="text-sm text-zinc-400 mt-1">{i.quantidade||1}x {i.nome}</p>)}</details><button disabled={busy===p.pedido_id} onClick={()=>entregar(p)} className="w-full bg-green-500 text-black py-4 rounded-xl font-black mt-3 disabled:opacity-50">{busy===p.pedido_id?"Confirmando...":"✅ Confirmar entrega + abrir WhatsApp"}</button></article>)}</div>}{msg&&<div className="sticky bottom-3 bg-zinc-800 border border-zinc-700 p-3 rounded-xl mt-4 text-center">{msg}</div>}</div></main>
}